import {test,expect} from 'bun:test'
import {chromium} from 'playwright'
import {build,type BuildMode} from '../../scripts/build'
import {resolve} from 'node:path'
import {rm} from 'node:fs/promises'
test('RFC08 L1222: Server-Timing spans use native navigation and resource responseStart',async()=>{
 const mode=(process.env.BUILD_MODE??'development') as BuildMode,dir=resolve('.build','server-performance-'+process.pid+'-'+mode)
 await build(dir,mode,{client:['tracks/records/server-performance-client.ts'],server:['tracks/records/server.tsx']});const module=await import(dir+'/server.js')
 const server=Bun.serve({port:0,hostname:'127.0.0.1',fetch:request=>{const path=new URL(request.url).pathname;if(path.startsWith('/_server'))return module.handle(request);if(path.endsWith('.js'))return new Response(Bun.file(dir+path),{headers:{'content-type':'text/javascript'}});return module.performanceDocument(request)}}),browser=await chromium.launch({channel:'chrome',headless:true})
 try{const page=await browser.newPage();await page.goto(String(server.url));await page.waitForFunction(()=>!!(window as any).serverPerformance);const result=await page.evaluate(()=>(window as any).serverPerformance.run());await Bun.write('artifacts/server-performance-'+mode+'.json',JSON.stringify(result,null,2));expect(result.result).toEqual({value:'perf'});if(mode==='production')expect(result.entries).toEqual([]);else{const nav=result.navigation[0];for(const metric of nav.serverTiming.filter((m:any)=>m.name==='solid-shell'||m.name==='solid-boundary')){const span=result.entries.find((e:any)=>metric.name==='solid-shell'?e.name==='shell · server':e.name.startsWith('boundary '));expect(span).toBeDefined();expect(Math.abs(span.start+span.duration-nav.responseStart)).toBeLessThan(0.001);expect(Math.abs(span.duration-metric.duration)).toBeLessThan(0.001)}expect(nav.serverTiming.some((m:any)=>m.name==='solid-boundary')).toBe(true);const call=result.calls[0],resource=result.resources.find((e:any)=>e.name===call.url),span=result.entries.find((e:any)=>e.name==='records-echo · server');expect(span).toBeDefined();expect(Math.abs(span.start+span.duration-resource.responseStart)).toBeLessThan(0.001);expect(span.detail.devtools.properties.some((p:any)=>p[0]==='Wire')).toBe(true)}
 const fallback=await page.evaluate(async()=>{const active=await(window as any).serverPerformance.cache(false);try{return {result:active.result,calls:active.calls,entries:active.snapshot()}}finally{active.close()}});expect(fallback.result).toBe(17);if(mode==='production')expect(fallback.entries).toEqual([]);else{expect(fallback.entries).toHaveLength(1);const span=fallback.entries[0],call=fallback.calls[0];expect(Math.abs(span.start+span.duration/2-call.at-call.durationMs/2)).toBeLessThan(0.001);expect(span.detail.devtools.properties.some((p:any)=>p[0]==='Placement'&&p[1].includes('centred'))).toBe(true)}
 }finally{await browser.close();server.stop(true);module.stop();await rm(dir,{recursive:true,force:true})}
},60000)
