import {$$registry,$$component} from 'solid-js/refresh'
import {OBSERVE,createComponent,createRoot,createSignal,createStore,createMemo,createOptimistic,action,refresh,flush,untrack,createEffect,createRenderEffect,mapArray,onCleanup,reconcile,Loading,For,Show} from 'solid-js'
import {attribution,feedback,graphSize,costs,type AttributionOptions} from 'solid-js/attribution'
import {isDev,isServer,render} from '@solidjs/web'
import {ticks,deferred} from '../../harness/timing'
import {equal,ok,type DocCase} from './registry'
const cases:DocCase[]=[]
const quiet:AttributionOptions={hotRuns:false,hotTime:false,wideDeps:false,fanOut:false,unstableMemos:false,wastedRecompute:false,holds:false,longHolds:false,stackedHolds:false,optimisticReverts:false,waterfalls:false,abandonedFlights:false,fallbackFlashes:false,graphGrowth:false}
function doc(id:string,line:number,statement:string,run:DocCase['run']){cases.push({id:'08/cost-'+id,file:'08-dev-diagnostics.md',statement:`L${line}: ${statement}`,run})}
type ProbeEvent={nodeName?:string;code:string;kind:string;severity:string;message:string;data:Record<string,any>;ownerPath?:string[]}
// Runtime probes assert the documented diagnostic payload; positive code counts establish the narrowed shape.
async function capture(run:(events:readonly ProbeEvent[])=>void|Promise<void>){const session=OBSERVE?.diagnostics.capture(),warn=console.warn;console.warn=()=>{};try{const events=(session?.events??[]) as unknown as readonly ProbeEvent[];await run(events);if(isDev)for(const event of events){if(['HUGE_FAN_OUT','HUGE_FAN_IN'].includes(event.code)){equal(event.kind,'graph');equal(event.severity,'warn')}else if(['HOT_SCOPE_RERUNS','HOT_SCOPE_TIME','WIDE_SCOPE_DEPS','UNSTABLE_MEMO_OUTPUT','WASTED_RECOMPUTE','GRAPH_GROWTH','EFFECT_RELAY_TEAR'].includes(event.code)){equal(event.kind,'perf');ok(['warn','info'].includes(event.severity))}else if(event.code==='FALLBACK_FLASH'){equal(event.kind,'responsiveness');equal(event.severity,'info')}}return [...events]}finally{session?.stop();console.warn=warn}}
function withEngine(opts:AttributionOptions,work:()=>void){const release=attribution.enable({...quiet,...opts});try{work()}finally{release()}}
if(!isServer){
 doc('fanout-core-threshold',419,'Always on core threshold 2000; unchanged writes silent; once per node, re-warning after growth 500; disposed subscribers do not count.',async()=>{
 const events=await capture(list=>{let close!:()=>void,write!:(n:number)=>void,read!:()=>number,add!:(count:number)=>()=>void;createRoot(d=>{close=d;[read,write]=createSignal(0);add=count=>{let dispose!:()=>void;createRoot(d=>{dispose=d;for(let i=0;i<count;i++)createMemo(read)});return dispose}});const off=add(2000);const reports=()=>list.filter(e=>e.code==='HUGE_FAN_OUT');try{equal(reports().length,0);write(0);flush();equal(reports().length,0);write(1);flush();equal(reports().length,isDev?1:0);if(isDev)equal(reports()[0]!.data.count,2000);write(2);flush();equal(reports().length,isDev?1:0);const stop=add(500);write(3);flush();equal(reports().length,isDev?2:0);if(isDev)equal(reports()[1]!.data.count,2500);stop();write(4);flush();equal(reports().length,isDev?2:0);off();write(5);flush();equal(reports().length,isDev?2:0)}finally{close()}});if(isDev)equal(events.filter(e=>e.code==='HUGE_FAN_OUT').every(e=>e.severity==='warn'),true)
 })
 doc('fanout-engine-handover',419,'Attribution default fanOut 250, at 2000 the core alone reports, no duplicate finding.',async()=>{
 for(const count of [249,250,2000]){const events=await capture(()=>withEngine({fanOut:undefined},()=>{let close!:()=>void,write!:(n:number)=>void;createRoot(d=>{close=d;const[r,w]=createSignal(0);write=w;for(let i=0;i<count;i++)createMemo(r)});try{write(1);flush()}finally{close()}}));const found=events.filter(e=>e.code==='HUGE_FAN_OUT');equal(found.length,isDev&&count>=250?1:0);if(isDev&&count===250){equal(found[0]!.data.count,250);equal(found[0]!.data.write,'write')}}
 })
 doc('fanout-invalidation-kinds',419,'Memo commit and async landing have core fan-out; stamped store write, refresh and async landing name data.write.',async()=>{for(const kind of ['memo','store','refresh','async'] as const){const events=await capture(async()=>{const release=attribution.enable({...quiet,fanOut:kind==='memo'?false:undefined});let close!:()=>void,trigger!:()=>unknown,read!:()=>number;const gate=deferred<number>();try{createRoot(d=>{close=d;if(kind==='store'){const[state,set]=createStore({n:0});read=()=>state.n;trigger=()=>set(d=>{d.n=1})}else if(kind==='memo'){const[s,set]=createSignal(0);read=createMemo(()=>s()*2);trigger=()=>set(1)}else if(kind==='refresh'){let n=0;const source=createMemo(()=>++n);read=source;trigger=()=>refresh(source)}else{read=createMemo(()=>gate.promise,{loadingValue:0});trigger=()=>gate.resolve(1)}for(let i=0;i<(kind==='memo'?2000:250);i++)createMemo(read)});flush();await trigger();await ticks(8);flush();equal(untrack(read),kind==='memo'||kind==='refresh'?2:1)}finally{close();release()}});const found=events.filter(e=>e.code==='HUGE_FAN_OUT');equal(found.length,isDev?1:0);if(isDev){equal(found[0]!.data.count,kind==='memo'?2000:250);if(kind!=='memo')equal(found[0]!.data.write,kind==='async'?'write':kind==='store'?'write':kind)}}})
 doc('wide-default-threshold',445,'Default dependency count 200, re-warns after another 50% growth, names sources.',async()=>{
 for(const count of [199,200]){const events=await capture(()=>withEngine({wideDeps:undefined},()=>{let close!:()=>void;createRoot(d=>{close=d;const reads=Array.from({length:count},(_,i)=>createSignal(0,{name:'s'+i})[0]);createMemo(()=>reads.reduce((n,r)=>n+r(),0),{name:'wide'});flush()});close()}));const found=events.filter(e=>e.code==='WIDE_SCOPE_DEPS');equal(found.length,isDev&&count===200?1:0);if(isDev&&count===200){equal(found[0]!.data.depCount,200);ok(found[0]!.message.includes('s0'))}}
 })
 doc('wide-growth-default',445,'Rewarn only after fifty-percent dependency growth; removed and repeated sources do not inflate the count.',async()=>{const events=await capture(list=>withEngine({wideDeps:undefined},()=>{const stops:(()=>void)[]=[];const readers:(()=>number)[]=[];let write!:(n:number)=>void;createRoot(d=>{stops.push(d);for(let i=0;i<199;i++)readers.push(createSignal(0)[0]);const[tick,set]=createSignal(0);write=set;createMemo(()=>{tick();return readers.reduce((n,r)=>n+r()+r(),0)})});const reports=()=>list.filter(e=>e.code==='WIDE_SCOPE_DEPS');try{equal(reports().length,isDev?1:0);createRoot(d=>{stops.push(d);for(let i=0;i<99;i++)readers.push(createSignal(0)[0])});write(1);flush();equal(reports().length,isDev?1:0);createRoot(d=>{stops.push(d);readers.push(createSignal(0)[0])});write(2);flush();equal(reports().length,isDev?2:0);if(isDev){equal(reports().map(e=>e.data.depCount),[200,300]);equal(reports().map(e=>e.severity),['warn','warn'])}}finally{for(const stop of stops)stop()}}));})
 doc('hot-runs-default',443,'Default 120 runs in 1000ms, with most recent cause chain.',async()=>{
 const events=await capture(()=>withEngine({hotRuns:undefined},()=>{let close!:()=>void,write!:(n:number)=>void;createRoot(d=>{close=d;const[r,w]=createSignal(0,{name:'hot-source'});write=w;createMemo(r,{name:'hot-reader'})});try{for(let n=1;n<=125;n++){write(n);flush()}}finally{close()}}));const found=events.filter(e=>e.code==='HOT_SCOPE_RERUNS');equal(found.length,isDev?1:0);if(isDev){ok(found[0]!.data.runs>=120);equal(found[0]!.data.windowMs,1000);ok(found[0]!.message.includes('hot-source'))}
 })
 doc('hot-time-default',444,'Default self-time budget 8ms in 1000ms.',async()=>{
 for(const costly of [false,true]){const events=await capture(()=>withEngine({hotTime:undefined},()=>{let close!:()=>void,write!:(n:number)=>void;createRoot(d=>{close=d;const[r,w]=createSignal(0);write=w;createMemo(()=>{const n=r();if(costly&&n){const end=performance.now()+12;while(performance.now()<end){}}return n})});try{write(1);flush()}finally{close()}}));const found=events.filter(e=>e.code==='HOT_SCOPE_TIME');equal(found.length,isDev&&costly?1:0);if(isDev&&costly){ok(found[0]!.data.spentMs>=8);equal(found[0]!.data.budgetMs,8);equal(found[0]!.data.windowMs,1000)}}
 })
 doc('unstable-default-and-equality',471,'Default four fresh shallow-equivalent runs; stable references or custom equals absorb the churn.',async()=>{
 for(const stable of [false,true]){const events=await capture(()=>withEngine({unstableMemos:undefined},()=>{let close!:()=>void,write!:(n:number)=>void;createRoot(d=>{close=d;const[r,w]=createSignal(0);write=w;const value=[1];const out=createMemo(()=>{r();return stable?value:[1]});createMemo(()=>out().length)});try{for(let n=1;n<=5;n++){write(n);flush()}}finally{close()}}));const found=events.filter(e=>e.code==='UNSTABLE_MEMO_OUTPUT');equal(found.length,isDev&&!stable?1:0);if(isDev&&!stable)ok(found[0]!.data.runs>=4)}
 })
 doc('wasted-default-and-output',477,'Default minRuns5, unchanged ratio .8, compute budget2ms, window1000; undefined outputs exempt.',async()=>{
 for(const sideOnly of [false,true]){const records:any[]=[];const off=OBSERVE?.records.subscribe('rerun',e=>{if(e.nodeName==='waste-output')records.push(e)});const events=await capture(()=>withEngine({wastedRecompute:undefined},()=>{let close!:()=>void,write!:(n:number)=>void;createRoot(d=>{close=d;const[r,w]=createSignal(0);write=w;createMemo(()=>{r();const end=performance.now()+0.7;while(performance.now()<end){};return sideOnly?undefined:0},{name:'waste-output'})});try{for(let n=1;n<=7;n++){write(n);flush()}}finally{close()}}));off?.();if(OBSERVE&&sideOnly){ok(records.length>0);ok(records.every(e=>e.changed===true))};const found=events.filter(e=>e.code==='WASTED_RECOMPUTE');equal(found.length,isDev&&!sideOnly?1:0);if(isDev&&!sideOnly){ok(found[0]!.data.runs>=5);ok(found[0]!.data.wasted/found[0]!.data.runs>=.8);ok(found[0]!.data.wastedMs>=2);equal(found[0]!.data.windowMs,1000);ok(Array.isArray(found[0]!.data.causes))}}
 })
 doc('fanin-core-threshold',425,'One recompute tracked 2000 distinct sources; repeated reads excluded.',async()=>{for(const count of [1999,2000]){const events=await capture(()=>{let close!:()=>void;createRoot(d=>{close=d;const sources=Array.from({length:count},()=>createSignal(0)[0]);createMemo(()=>sources.reduce((n,r)=>n+r()+r(),0))});close()});equal(events.filter(e=>e.code==='HUGE_FAN_IN').length,isDev&&count===2000?1:0)}})
 doc('graph-growth-default',433,'Default 3 consecutive visits and ratio1.25, with history/routing metadata; initial declarations exempt.',async()=>{
 for(const leak of [false,true]){const events=await capture(list=>withEngine({graphGrowth:undefined},()=>{const stops:(()=>void)[]=[];const add=()=>{createRoot(d=>{stops.push(d);const[r]=createSignal(0);for(let i=0;i<4;i++)createMemo(r)})};try{for(let visit=0;visit<3;visit++){if(leak||visit===0)add();OBSERVE?.attribution.withOrigin({kind:'navigation',name:'/growth',to:'/growth',initial:visit===0},()=>{});flush()};equal(list.filter(e=>e.code==='GRAPH_GROWTH').length,0);if(leak)add();OBSERVE?.attribution.withOrigin({kind:'navigation',name:'/growth',to:'/growth'},()=>{});flush()}finally{for(const stop of stops)stop()}}));const found=events.filter(e=>e.code==='GRAPH_GROWTH');equal(found.length,isDev&&leak?1:0);if(isDev&&leak){equal(found[0]!.data.route,'/growth');equal(found[0]!.data.history.length,3);ok(found[0]!.data.grew.includes('computations'));ok(found[0]!.data.roots>=1);equal(found[0]!.data.routes,['/growth']);for(const row of found[0]!.data.history)for(const series of ['owners','computations','signals','edges'])ok(Number.isInteger(row[series])&&row[series]>=0);for(const series of found[0]!.data.grew){const values=found[0]!.data.history.map((row:any)=>row[series]);ok(values[1]>values[0]&&values[2]>values[1]);ok(values[2]>=values[0]*1.25)};equal(found[0]!.data.interaction,undefined);equal(found[0]!.severity,'warn')}}
 })
 doc('graph-growth-routes-subject',433,'The whole graph leaks at every visited route; the first completed climb names the other routes then resets, with no live subject.',async()=>{const subjects:unknown[]=[];const off=OBSERVE?.diagnostics.subscribe((e,s)=>{if(e.code==='GRAPH_GROWTH')subjects.push(s)});const events=await capture(()=>withEngine({graphGrowth:undefined},()=>{const stops:(()=>void)[]=[];try{for(let visit=0;visit<4;visit++)for(const route of ['/growth-one','/growth-two']){createRoot(d=>{stops.push(d);const[r]=createSignal(0);for(let i=0;i<5;i++)createMemo(r)});OBSERVE?.attribution.withInteraction({type:'click',target:'button#route'},()=>OBSERVE!.attribution.withOrigin({kind:'navigation',name:route,to:route,initial:visit===0},()=>{}));flush()}}finally{for(const stop of stops)stop()}}));off?.();const found=events.filter(e=>e.code==='GRAPH_GROWTH');equal(found.length,OBSERVE?1:0);if(OBSERVE){equal(found[0]!.data.route,'/growth-one');equal([...found[0]!.data.routes].sort(),['/growth-one','/growth-two']);equal(found[0]!.data.history.length,3);equal(found[0]!.data.interaction.target,'button#route');equal(subjects.length,1);ok(subjects.every(s=>s==null))}})
 doc('graph-reachability-disposal',437,'Only graph-reachable ownerless computations count; disposal removes a root; false disables growth warnings.',async()=>{const events=await capture(()=>withEngine({graphGrowth:false},()=>{const before=graphSize();const [external]=createSignal(1);createEffect(external,()=>{});flush();equal(graphSize(),before);let close!:()=>void;createRoot(d=>{close=d;createMemo(external)});const during=graphSize();if(isDev){ok(during.owners>before.owners);ok(during.computations>=before.computations+2);ok(during.signals>before.signals)}close();equal(graphSize(),before);const stops:(()=>void)[]=[];try{for(let i=0;i<5;i++){createRoot(d=>{stops.push(d);const[r]=createSignal(0);createMemo(r)});OBSERVE?.attribution.withOrigin({kind:'navigation',name:'/disabled-growth',to:'/disabled-growth'},()=>{});flush()}}finally{for(const stop of stops)stop()}}));equal(events.filter(e=>e.code==='GRAPH_GROWTH'),[])})
 doc('fallback-flash-default',555,'Fallback displayed under150ms emits one info channel event; off disables reporting but not the fold count.',async()=>{
 for(const enabled of [false,true]){const target=document.createElement('div');document.body.appendChild(target);const gate=deferred<number>();let dispose!:()=>void;const events=await capture(async()=>{const release=attribution.enable({...quiet,fallbackFlashes:enabled});try{dispose=render(()=>{const n=createMemo(()=>gate.promise);return <Loading fallback='flash'><span>{n()}</span></Loading>},target);equal(target.textContent,'flash');await ticks(2);gate.resolve(1);await ticks(5);flush();equal(target.textContent,'1');if(isDev)ok(feedback().fallbacks.some(row=>row.flashes>=1))}finally{dispose();release();target.remove()}});const found=events.filter(e=>e.code==='FALLBACK_FLASH');equal(found.length,isDev&&enabled?1:0);if(isDev&&enabled){ok(found[0]!.data.shownMs<150);ok(found[0]!.ownerPath===undefined||Array.isArray(found[0]!.ownerPath))}}
 })
 doc('effect-relay-tear',494,'A derivable single-writer identity relay warns; direct derivation stays quiet.',async()=>{
 for(const relay of [false,true]){const events=await capture(()=>withEngine({},()=>{let close!:()=>void,write!:(n:number)=>void;createRoot(d=>{close=d;const[r,w]=createSignal(0,{name:'root'});write=w;const[copy,set]=createSignal(0,{name:'copy'});if(relay)createEffect(r,n=>{set(n)});const value=relay?copy:createMemo(r);createEffect(()=>r()+value(),()=>{})});try{flush();for(let i=1;i<=3;i++){write(i);flush()}}finally{close()}}));const found=events.filter(e=>e.code==='EFFECT_RELAY_TEAR');equal(found.length>0,isDev&&relay);if(isDev&&relay)ok(found.some(e=>e.severity==='warn'))}
 })

 doc('effect-cycle-families',483,'Own writes may feed back through derived store reads; two-effect rings report info; unrelated untracked writes remain quiet.',async()=>{for(const mode of ['store','ring','untrack'] as const){let final=0;const events=await capture(()=>withEngine({},()=>{let close!:()=>void,trigger!:()=>void,read!:()=>number;createRoot(d=>{close=d;if(mode==='store'){const[state,set]=createStore({n:0});const a=createMemo(()=>state.n*2,{name:'step-a'});const b=createMemo(()=>a()/2,{name:'step-b'});createEffect(b,n=>{if(n%2)set(d=>{d.n=n+1})},{name:'normalize'});read=()=>state.n;trigger=()=>set(d=>{d.n=3})}else{const[a,setA]=createSignal(0),[b,setB]=createSignal(0);read=a;trigger=()=>setA(1);createEffect(a,n=>{if(n&&n<5)setB(n+1)},{name:'relay-a'});if(mode==='ring')createEffect(b,n=>{if(n&&n<5)setA(n+1)},{name:'relay-b'});else createEffect(()=>0,()=>{untrack(b)})}});try{flush();trigger();flush();final=untrack(read)}finally{close()}}));equal(final,mode==='store'?4:mode==='ring'?5:1);const found=events.filter(e=>e.code==='EFFECT_WRITES_OWN_SOURCE');equal(found.length,isDev&&mode!=='untrack'?1:0);if(isDev&&mode!=='untrack'){equal(found[0]!.kind,'perf');equal(found[0]!.severity,mode==='ring'?'info':'warn');equal(found[0]!.data.effects.length,mode==='ring'?2:1);equal(found[0]!.data.flushes,mode==='ring'?3:2)}}})
 doc('relay-advisory-and-escalation',497,'Other writers make an identity reset info; transformed callback outputs tear once at info and repeatedly at warn.',async()=>{for(const mode of ['reset','transform'] as const){const snapshots:string[]=[];const events=await capture(list=>withEngine({},()=>{let close!:()=>void,write!:(n:string)=>void,edit!:(n:string)=>void;createRoot(d=>{close=d;const [read,set]=createSignal('');write=set;const[local,setLocal]=createSignal('');edit=setLocal;createEffect(read,v=>{setLocal(mode==='transform'?v+'!':v)});createEffect(()=>read()+'/'+local(),v=>{snapshots.push(v)})});try{flush();if(mode==='reset'){edit('typed');flush()};snapshots.length=0;write('a');flush();equal(snapshots,mode==='reset'?['a/typed','a/a']:['a/!','a/a!']);const reports=()=>list.filter(e=>e.code==='EFFECT_RELAY_TEAR');equal(reports().length,isDev?1:0);if(isDev){equal(reports()[0]!.severity,'info');equal(reports()[0]!.data.copy,mode==='reset');equal(reports()[0]!.data.soleWriter,mode!=='reset')};if(mode==='transform'){for(const n of ['b','c','d','e']){write(n);flush()};if(isDev){equal(reports().map(e=>e.severity),['info','warn']);equal(reports()[1]!.data.occurrences,3)}}}finally{close()}}));}})
 doc('async-waterfall-tiers',463,'Depth2 is info channel-only; depth3 warns; all proven chains remain in history.',async()=>{for(const depth of [2,3]){const events=await capture(async()=>{const release=attribution.enable({...quiet,waterfalls:{minFlightMs:0}});let close!:()=>void;const first=deferred<number>();try{createRoot(d=>{close=d;const a=createMemo(()=>first.promise,{name:'first'});const b=createMemo(()=>{a();return Promise.resolve(2)},{name:'second'});const c=depth===3?createMemo(()=>{b();return Promise.resolve(3)},{name:'third'}):b;createEffect(c,()=>{})});flush();first.resolve(1);await ticks(12);flush();if(isDev)ok(attribution.history('waterfall').length>0)}finally{close();release()}});const found=events.filter(e=>e.code==='ASYNC_WATERFALL');if(isDev){ok(found.length>0);for(const event of found){equal(event.kind,'perf');equal(event.severity,event.data.chain.length>=3?'warn':'info');ok(event.data.chain.every((link:any)=>link.ms>=0));ok(event.data.sequentialMs>=0)}equal(found.some(e=>e.severity==='warn'),depth===3)}else equal(found,[])}})
 doc('waterfall-default-duration',463,'Each link must reach default50ms; fast cached tails remain in history without warnings.',async()=>{for(const ms of [0,49,50,51]){let clock=1000,close!:()=>void;const descriptor=Object.getOwnPropertyDescriptor(performance,'now');Object.defineProperty(performance,'now',{configurable:true,value:()=>clock});const first=deferred<number>(),second=deferred<number>();const opts={...quiet};delete opts.waterfalls;const release=attribution.enable(opts);try{const events=await capture(async()=>{createRoot(d=>{close=d;const a=createMemo(()=>first.promise,{name:'duration-first'});const b=createMemo(()=>{a();return second.promise},{name:'duration-second'});createEffect(b,()=>{})});flush();clock+=ms;first.resolve(1);await ticks(8);clock+=ms;second.resolve(2);await ticks(8);flush();if(OBSERVE){const history=attribution.history('waterfall');equal(history.length,1);equal(history[0]!.chain.map(l=>l.ms),[ms,ms]);equal(history[0]!.sequentialMs,2*ms)}});equal(events.filter(e=>e.code==='ASYNC_WATERFALL').length,OBSERVE&&ms>=50?1:0)}finally{first.resolve(1);second.resolve(2);close();release();if(descriptor)Object.defineProperty(performance,'now',descriptor);else delete(performance as any).now}}})
 doc('waterfall-node-growth',463,'A node warns once per chain depth and warns again only after its sequential chain grows.',async()=>{let clock=1000,close!:()=>void,write!:(v:number)=>void;const gates=Array.from({length:3},()=>[deferred<number>(),deferred<number>(),deferred<number>()]);const descriptor=Object.getOwnPropertyDescriptor(performance,'now');Object.defineProperty(performance,'now',{configurable:true,value:()=>clock});const release=attribution.enable({...quiet,waterfalls:{minFlightMs:50}});try{await capture(async events=>{createRoot(d=>{close=d;const[cycle,set]=createSignal(0);write=set;const a=createMemo(()=>gates[cycle()]![0]!.promise,{name:'grow-first'});const b=createMemo(()=>{a();return gates[untrack(cycle)]![1]!.promise},{name:'grow-middle'});const last=createMemo(()=>{const n=untrack(cycle);if(n===2)b();else a();return gates[n]![2]!.promise},{name:'grow-last'});createEffect(last,()=>{})});flush();for(let n=0;n<3;n++){if(n){write(n);flush()};clock+=50;gates[n]![0]!.resolve(n*10+1);await ticks(8);clock+=50;if(n===2){gates[n]![1]!.resolve(n*10+2);await ticks(8);clock+=50};gates[n]![2]!.resolve(n*10+3);await ticks(8);flush();equal(events.filter(e=>e.code==='ASYNC_WATERFALL'&&e.nodeName==='grow-last').length,OBSERVE?(n===2?2:1):0)};if(OBSERVE)equal(events.filter(e=>e.code==='ASYNC_WATERFALL'&&e.nodeName==='grow-last').map(e=>e.data.chain.length),[2,3])})}finally{for(const list of gates)for(const gate of list)gate.resolve(1);close();release();if(descriptor)Object.defineProperty(performance,'now',descriptor);else delete(performance as any).now}})
 doc('wasted-overlay-phases',477,'Plain equality-cutoff self-time folds wastedMs; held and optimistic work folds overlayMs without WASTED_RECOMPUTE blame.',async()=>{
 for(const mode of ['plain','held','optimistic'] as const){let close!:()=>void,write!:(n:number)=>void,run!:(n:number)=>Promise<void>,clock=1000;const records:any[]=[];const off=OBSERVE?.records.subscribe('rerun',e=>{if(e.nodeName==='overlay-cost')records.push(e)});const gate=deferred<void>(),descriptor=Object.getOwnPropertyDescriptor(performance,'now');Object.defineProperty(performance,'now',{configurable:true,value:()=>clock});const release=attribution.enable({...quiet,wastedRecompute:{budgetMs:2,minRuns:5,ratio:.8,windowMs:1000}});try{const events=await capture(async()=>{createRoot(d=>{close=d;const[r,w]=mode==='optimistic'?createOptimistic(0):createSignal(0);write=w;const output=createMemo(()=>{r();clock++;return 0},{name:'overlay-cost'});createEffect(output,()=>{});if(mode==='held'){const blocker=createMemo<number|void>(()=>r()?gate.promise:0);createRenderEffect(blocker,()=>{})};run=action(function*(n:number){w(n);yield gate.promise})});flush();if(mode==='plain'){for(let n=1;n<=7;n++){write(n);flush()}}else{const pending:Promise<void>[]=[];for(let n=1;n<=7;n++){if(mode==='held')write(n);else pending.push(run(n));flush()};await ticks(3);gate.resolve();await Promise.all(pending);await ticks(4);flush()};if(OBSERVE){const row=costs().scopes.find(s=>s.name==='overlay-cost');ok(row,JSON.stringify(costs()));equal(row!.runs,records.length);equal(row!.selfMs,records.reduce((sum,e)=>sum+e.selfMs,0));equal(row!.overlayMs,records.filter(e=>e.phase!=='plain').reduce((sum,e)=>sum+e.selfMs,0));equal(row!.wastedMs,records.filter(e=>e.phase==='plain'&&!e.held&&!e.changed).reduce((sum,e)=>sum+e.selfMs,0));const table=costs();equal(table.scopes.map(r=>r.selfMs),table.scopes.map(r=>r.selfMs).sort((a,b)=>b-a));equal(table.writes.map(r=>r.downstreamMs),table.writes.map(r=>r.downstreamMs).sort((a,b)=>b-a));if(mode==='plain'){ok(row!.wastedMs>=5);equal(row!.overlayMs,0)}else{ok(row!.wastedMs<=1,JSON.stringify(row));ok(row!.overlayMs>0,JSON.stringify(row))}}});equal(events.some(e=>e.code==='WASTED_RECOMPUTE'),!!OBSERVE&&mode==='plain')}finally{gate.resolve();close();off?.();release();if(descriptor)Object.defineProperty(performance,'now',descriptor);else delete(performance as any).now}}
 })
 doc('hot-fanout-milestones',455,'One culprit gets one per-scope warning; additional hot scopes fold at fixed5/50/500 milestones with no subject and one cause.',async()=>{for(const count of [1,4,501]){const subjects:unknown[]=[];const off=OBSERVE?.diagnostics.subscribe((event,subject)=>{if(event.code==='HOT_SCOPE_FANOUT')subjects.push(subject)});const events=await capture(()=>withEngine({hotRuns:{count:1,windowMs:1000}},()=>{let close!:()=>void,write!:(n:number)=>void;createRoot(d=>{close=d;const[r,w]=createSignal(0,{name:'fanout-source'});write=w;for(let i=0;i<count;i++)createMemo(r,{name:'victim-'+i})});try{write(1);flush()}finally{close()}}));off?.();const fanout=events.filter(e=>e.code==='HOT_SCOPE_FANOUT'),expected=count===501?[5,50,500]:[];equal(fanout.map(e=>e.data.scopes),OBSERVE?expected:[]);equal(events.filter(e=>e.code==='HOT_SCOPE_RERUNS').length,OBSERVE?1:0);if(OBSERVE)for(const event of fanout){equal(event.kind,'perf');equal(event.severity,'warn');equal(event.data.runs,event.data.scopes);equal(event.data.windowMs,1000);ok(event.data.cause.includes('fanout-source'));equal(event.nodeName,event.data.cause);equal(event.ownerPath,undefined)};ok(subjects.every(s=>s==null))}})
 doc('store-copy-paths',504,'Copies compare unwrapped leaves, warn once per path, and rerun container readers; draft mutation, reconcile and wholesale replacement remain quiet.',async()=>{for(const mode of ['object-copy','array-copy','draft','reconcile','turnover'] as const){let containerRuns=0;const events=await capture(()=>withEngine({},()=>{let close!:()=>void,set!:ReturnType<typeof createStore<{box:any}>>[1];createRoot(d=>{close=d;const[s,w]=createStore<{box:any}>({box:mode==='array-copy'?[{n:1},{n:2},{n:3},{n:4}]:{a:1,b:{n:2},c:3,d:4}},{name:'copy-'+mode});set=w;createEffect(()=>s.box,()=>{containerRuns++})});try{flush();if(mode==='array-copy'){set(d=>{d.box=[...d.box,{n:5}]});flush();set(d=>{d.box=[...d.box,{n:6}]})}else if(mode==='object-copy'){set(d=>{d.box={...d.box,a:2}});flush();set(d=>{d.box={...d.box,a:3}})}else if(mode==='draft')set(d=>{d.box.a=2});else if(mode==='reconcile')set(d=>{reconcile({a:2,b:{n:2},c:3,d:4})(d.box)});else set(d=>{d.box={a:11,b:{n:12},c:13,d:14}});flush();equal(containerRuns,mode==='object-copy'||mode==='array-copy'?3:mode==='turnover'?2:1)}finally{close()}}));const found=events.filter(e=>e.code==='IMMUTABLE_UPDATE_IN_STORE');equal(found.length,OBSERVE&&mode.endsWith('copy')?1:0);if(found.length){equal(found[0]!.kind,'perf');equal(found[0]!.severity,'warn');equal(found[0]!.data.shape,mode==='array-copy'?'array':'object');equal(found[0]!.data.total,mode==='array-copy'?5:4);equal(found[0]!.data.unchanged,mode==='array-copy'?4:3);equal(found[0]!.data.changed,1);ok(found[0]!.data.path.includes('box'))}}})
 doc('list-identity-shapes',510,'Equivalent rows pair by id/key/_id/position; key functions that churn blame keys, while stable keys, true turnover and small edits stay quiet.',async()=>{for(const field of ['id','key','_id','none'])for(const mode of ['identity','unstable','stable','turnover','small'] as const){let created=0,removed=0;const events=await capture(()=>withEngine({},()=>{let close!:()=>void,write!:(v:Record<string,number>[])=>void,read!:()=>Record<string,number>[];createRoot(d=>{close=d;const[r,w]=createSignal(Array.from({length:10},(_,n)=>field==='none'?{n,value:0}:{[field]:n,n,value:0}));read=r;write=w;const mount=()=>{created++;onCleanup(()=>{removed++});return created};const key=(item:Record<string,number>)=>item[field==='none'?'n':field];const mapped=mode==='stable'?mapArray(r,mount,{keyed:key}):mode==='unstable'?mapArray(r,mount,{keyed:item=>({key:key(item)})}):mapArray(r,mount);createMemo(mapped)});try{flush();equal(created,10);const old=untrack(read);write(mode==='small'?old.map((item,i)=>i===0?{...item,value:1}:item):old.map(item=>({...item,...(mode==='turnover'?{value:1}:{})})));flush();equal(created,mode==='stable'?10:mode==='small'?11:20);equal(removed,mode==='stable'?0:mode==='small'?1:10)}finally{close()}}));const found=events.filter(e=>e.code==='UNSTABLE_LIST_IDENTITY');equal(found.length,OBSERVE&&(mode==='identity'||mode==='unstable')?1:0);if(found.length){equal(found[0]!.kind,'perf');equal(found[0]!.severity,'warn');equal(found[0]!.data.keyed,mode==='unstable');equal(found[0]!.data.removed,10);equal(found[0]!.data.created,10);equal(found[0]!.data.length,10);equal(found[0]!.data.equivalent,found[0]!.data.sampled);if(mode==='unstable')ok(found[0]!.message.includes('key function'))}}})
 doc('engine-warning-gate',441,'All six cost-check perf warnings require an enabled engine; disabled instrumentation remains quiet.',async()=>{for(const enabled of [false,true]){let close!:()=>void,write!:(n:number)=>void,clock=1000;const descriptor=Object.getOwnPropertyDescriptor(performance,'now');Object.defineProperty(performance,'now',{configurable:true,value:()=>clock});const release=enabled?attribution.enable({...quiet,hotRuns:{count:1,windowMs:1000},hotTime:{budgetMs:0,windowMs:1000},wideDeps:1,fanOut:1,unstableMemos:1,wastedRecompute:{budgetMs:0,minRuns:1,ratio:0,windowMs:1000}}):()=>{};try{const events=await capture(()=>{createRoot(d=>{close=d;const[r,w]=createSignal(0);write=w;const[second]=createSignal(0);createMemo(()=>{r();second();clock++;return{}},{name:'gate-churn'});createMemo(()=>{r();clock++;return 0},{name:'gate-waste'})});for(let n=0;n<3;n++){write(n+1);flush()}});const codes=['HOT_SCOPE_RERUNS','HOT_SCOPE_TIME','WIDE_SCOPE_DEPS','HUGE_FAN_OUT','UNSTABLE_MEMO_OUTPUT','WASTED_RECOMPUTE'];for(const code of codes)equal(events.some(e=>e.code===code),!!OBSERVE&&enabled)}finally{close();release();if(descriptor)Object.defineProperty(performance,'now',descriptor);else delete(performance as any).now}}})
 doc('renderer-and-hmr-width',427,'Renderer child-resolution and HMR plumbing still reach HUGE_FAN_IN, while WIDE_SCOPE_DEPS excludes those framework widths.',async()=>{for(const family of ['renderer','hmr'])for(const count of [50,2500]){const target=document.createElement('div');let close!:()=>void;const events=await capture(()=>withEngine({wideDeps:200},()=>{if(family==='renderer'){close=render(()=>{const sources=Array.from({length:count},()=>createSignal(1)[0]);return <For each={sources}>{read=><Show when={read()}>{n=><span>{n()}</span>}</Show>}</For>},target);equal(target.textContent!.length,count)}else{createRoot(d=>{close=d;function Unit(){return <span>hot</span>};createComponent(Unit,{});const Hot=$$component($$registry(),'Unit',Unit);const rows=Array.from({length:count},()=>Hot({}));createMemo(()=>rows.map(v=>typeof v==='function'?(v as any)():v),{name:'hmr-combiner'})})};flush();close()}));const huge=events.filter(e=>e.code==='HUGE_FAN_IN');if(isDev){ok((huge.length>0)===(count>=2000),family+'/'+count+' huge='+JSON.stringify(huge));equal(events.filter(e=>e.code==='WIDE_SCOPE_DEPS'),[])}else if(!OBSERVE)equal(huge,[])}})
 doc('checks-false',419,'checks:false folds off six cost checks, fanOut:false leaves only core threshold.',async()=>{const events=await capture(()=>withEngine({checks:false,hotRuns:{count:1,windowMs:1000},hotTime:{budgetMs:0,windowMs:1000},wideDeps:1,fanOut:1,unstableMemos:1,wastedRecompute:{budgetMs:0,minRuns:1,ratio:0,windowMs:1000}},()=>{let close!:()=>void,write!:(n:number)=>void;createRoot(d=>{close=d;const[r,w]=createSignal(0);write=w;createMemo(()=>({n:(r(),0)}));createMemo(r)});try{write(1);flush()}finally{close()}}));equal(events.filter(e=>['HOT_SCOPE_RERUNS','HOT_SCOPE_TIME','WIDE_SCOPE_DEPS','HUGE_FAN_OUT','UNSTABLE_MEMO_OUTPUT','WASTED_RECOMPUTE'].includes(e.code)),[])})
}
export const costDiagnosticCases=cases
