import {OBSERVE,createRoot,createSignal,createMemo,flush,untrack,createEffect,Loading} from 'solid-js'
import {attribution,feedback,type AttributionOptions} from 'solid-js/attribution'
import {isDev,isServer,render} from '@solidjs/web'
import {ticks,deferred} from '../../harness/timing'
import {equal,ok,type DocCase} from './registry'
const cases:DocCase[]=[]
const quiet:AttributionOptions={hotRuns:false,hotTime:false,wideDeps:false,fanOut:false,unstableMemos:false,wastedRecompute:false,holds:false,longHolds:false,stackedHolds:false,optimisticReverts:false,waterfalls:false,abandonedFlights:false,fallbackFlashes:false,graphGrowth:false}
function doc(id:string,line:number,statement:string,run:DocCase['run']){cases.push({id:'08/cost-'+id,file:'08-dev-diagnostics.md',statement:`L${line}: ${statement}`,run})}
type ProbeEvent={code:string;kind:string;severity:string;message:string;data:Record<string,any>;ownerPath?:string[]}
// Runtime probes assert the documented diagnostic payload; positive code counts establish the narrowed shape.
async function capture(run:(events:readonly ProbeEvent[])=>void|Promise<void>){const session=OBSERVE?.diagnostics.capture(),warn=console.warn;console.warn=()=>{};try{const events=(session?.events??[]) as unknown as readonly ProbeEvent[];await run(events);if(isDev)for(const event of events){if(['HUGE_FAN_OUT','HUGE_FAN_IN'].includes(event.code)){equal(event.kind,'graph');equal(event.severity,'warn')}else if(['HOT_SCOPE_RERUNS','HOT_SCOPE_TIME','WIDE_SCOPE_DEPS','UNSTABLE_MEMO_OUTPUT','WASTED_RECOMPUTE','GRAPH_GROWTH','EFFECT_RELAY_TEAR'].includes(event.code)){equal(event.kind,'perf');ok(['warn','info'].includes(event.severity))}else if(event.code==='FALLBACK_FLASH'){equal(event.kind,'responsiveness');equal(event.severity,'info')}}return [...events]}finally{session?.stop();console.warn=warn}}
function withEngine(opts:AttributionOptions,work:()=>void){const release=attribution.enable({...quiet,...opts});try{work()}finally{release()}}
if(!isServer){
 doc('fanout-core-threshold',419,'Always on core threshold 2000; unchanged writes silent; once per node, re-warning after growth 500; disposed subscribers do not count.',async()=>{
 const events=await capture(list=>{let close!:()=>void,write!:(n:number)=>void,read!:()=>number,add!:(count:number)=>()=>void;createRoot(d=>{close=d;[read,write]=createSignal(0);add=count=>{let dispose!:()=>void;createRoot(d=>{dispose=d;for(let i=0;i<count;i++)createMemo(read)});return dispose}});const off=add(2000);const reports=()=>list.filter(e=>e.code==='HUGE_FAN_OUT');try{equal(reports().length,0);write(0);flush();equal(reports().length,0);write(1);flush();equal(reports().length,isDev?1:0);if(isDev)equal(reports()[0]!.data.count,2000);write(2);flush();equal(reports().length,isDev?1:0);const stop=add(500);write(3);flush();equal(reports().length,isDev?2:0);if(isDev)equal(reports()[1]!.data.count,2500);stop();write(4);flush();equal(reports().length,isDev?2:0);off();write(5);flush();equal(reports().length,isDev?2:0)}finally{close()}});if(isDev)equal(events.filter(e=>e.code==='HUGE_FAN_OUT').every(e=>e.severity==='warn'),true)
 })
 doc('fanout-engine-handover',419,'Attribution default fanOut 250, at 2000 the core alone reports, no duplicate finding.',async()=>{
 for(const count of [249,250,2000]){const events=await capture(()=>withEngine({fanOut:undefined},()=>{let close!:()=>void,write!:(n:number)=>void;createRoot(d=>{close=d;const[r,w]=createSignal(0);write=w;for(let i=0;i<count;i++)createMemo(r)});try{write(1);flush()}finally{close()}}));const found=events.filter(e=>e.code==='HUGE_FAN_OUT');equal(found.length,isDev&&count>=250?1:0);if(isDev&&count===250){equal(found[0]!.data.count,250);equal(found[0]!.data.write,'write')}}
 })
 doc('wide-default-threshold',445,'Default dependency count 200, re-warns after another 50% growth, names sources.',async()=>{
 for(const count of [199,200]){const events=await capture(()=>withEngine({wideDeps:undefined},()=>{let close!:()=>void;createRoot(d=>{close=d;const reads=Array.from({length:count},(_,i)=>createSignal(0,{name:'s'+i})[0]);createMemo(()=>reads.reduce((n,r)=>n+r(),0),{name:'wide'});flush()});close()}));const found=events.filter(e=>e.code==='WIDE_SCOPE_DEPS');equal(found.length,isDev&&count===200?1:0);if(isDev&&count===200){equal(found[0]!.data.depCount,200);ok(found[0]!.message.includes('s0'))}}
 })
 doc('wide-growth-default',445,'Rewarn only after fifty-percent dependency growth; removed and repeated sources do not inflate the count.',async()=>{const events=await capture(list=>withEngine({wideDeps:undefined},()=>{const stops:(()=>void)[]=[];const readers:(()=>number)[]=[];let write!:(n:number)=>void;createRoot(d=>{stops.push(d);for(let i=0;i<199;i++)readers.push(createSignal(0)[0]);const[tick,set]=createSignal(0);write=set;createMemo(()=>{tick();return readers.reduce((n,r)=>n+r()+r(),0)})});const reports=()=>list.filter(e=>e.code==='WIDE_SCOPE_DEPS');try{equal(reports().length,isDev?1:0);createRoot(d=>{stops.push(d);for(let i=0;i<99;i++)readers.push(createSignal(0)[0])});write(1);flush();equal(reports().length,isDev?1:0);createRoot(d=>{stops.push(d);readers.push(createSignal(0)[0])});write(2);flush();equal(reports().length,isDev?2:0);if(isDev){equal(reports().map(e=>e.data.depCount),[200,300]);equal(reports().map(e=>e.severity),['warn','warn'])}}finally{for(const stop of stops)stop()}}));})
 doc('hot-runs-default',443,'Default 120 runs in 1000ms, with most recent cause chain.',async()=>{
 const events=await capture(()=>withEngine({hotRuns:undefined},()=>{let close!:()=>void,write!:(n:number)=>void;createRoot(d=>{close=d;const[r,w]=createSignal(0,{name:'hot-source'});write=w;createMemo(r,{name:'hot-reader'})});try{for(let n=1;n<=125;n++){write(n);flush()}}finally{close()}}));const found=events.filter(e=>e.code==='HOT_SCOPE_RERUNS');equal(found.length,isDev?1:0);if(isDev){ok(found[0]!.data.runs>=120);equal(found[0]!.data.windowMs,1000);ok(found[0]!.message.includes('hot-source'))}
 })
 doc('hot-time-default',444,'Default self-time budget 8ms in 1000ms.',async()=>{
 for(const costly of [false,true]){const events=await capture(()=>withEngine({hotTime:undefined},()=>{let close!:()=>void,write!:(n:number)=>void;createRoot(d=>{close=d;const[r,w]=createSignal(0);write=w;createMemo(()=>{const n=r();if(costly&&n){const end=performance.now()+12;while(performance.now()<end){}}return n})});try{write(1);flush()}finally{close()}}));const found=events.filter(e=>e.code==='HOT_SCOPE_TIME');equal(found.length,isDev&&costly?1:0);if(isDev&&costly){ok(found[0]!.data.spentMs>=8);equal(found[0]!.data.budgetMs,8);equal(found[0]!.data.windowMs,1000)}}
 })
 doc('unstable-default-and-equality',471,'Default four fresh shallow-equivalent runs; stable references or custom equals absorb the churn.',async()=>{
 for(const stable of [false,true]){const events=await capture(()=>withEngine({unstableMemos:undefined},()=>{let close!:()=>void,write!:(n:number)=>void;createRoot(d=>{close=d;const[r,w]=createSignal(0);write=w;const value=[1];const out=createMemo(()=>{r();return stable?value:[1]});createMemo(()=>out().length)});try{for(let n=1;n<=5;n++){write(n);flush()}}finally{close()}}));const found=events.filter(e=>e.code==='UNSTABLE_MEMO_OUTPUT');equal(found.length,isDev&&!stable?1:0);if(isDev&&!stable)ok(found[0]!.data.runs>=4)}
 })
 doc('wasted-default-and-output',477,'Default minRuns5, unchanged ratio .8, compute budget2ms, window1000; undefined outputs exempt.',async()=>{
 for(const sideOnly of [false,true]){const events=await capture(()=>withEngine({wastedRecompute:undefined},()=>{let close!:()=>void,write!:(n:number)=>void;createRoot(d=>{close=d;const[r,w]=createSignal(0);write=w;createMemo(()=>{r();const end=performance.now()+0.7;while(performance.now()<end){};return sideOnly?undefined:0})});try{for(let n=1;n<=7;n++){write(n);flush()}}finally{close()}}));const found=events.filter(e=>e.code==='WASTED_RECOMPUTE');equal(found.length,isDev&&!sideOnly?1:0);if(isDev&&!sideOnly){ok(found[0]!.data.runs>=5);ok(found[0]!.data.wasted/found[0]!.data.runs>=.8);ok(found[0]!.data.wastedMs>=2);equal(found[0]!.data.windowMs,1000);ok(Array.isArray(found[0]!.data.causes))}}
 })
 doc('fanin-core-threshold',425,'One recompute tracked 2000 distinct sources; repeated reads excluded.',async()=>{for(const count of [1999,2000]){const events=await capture(()=>{let close!:()=>void;createRoot(d=>{close=d;const sources=Array.from({length:count},()=>createSignal(0)[0]);createMemo(()=>sources.reduce((n,r)=>n+r()+r(),0))});close()});equal(events.filter(e=>e.code==='HUGE_FAN_IN').length,isDev&&count===2000?1:0)}})
 doc('graph-growth-default',433,'Default 3 consecutive visits and ratio1.25, with history/routing metadata; initial declarations exempt.',async()=>{
 for(const leak of [false,true]){const events=await capture(list=>withEngine({graphGrowth:undefined},()=>{const stops:(()=>void)[]=[];const add=()=>{createRoot(d=>{stops.push(d);const[r]=createSignal(0);for(let i=0;i<4;i++)createMemo(r)})};try{for(let visit=0;visit<3;visit++){if(leak||visit===0)add();OBSERVE?.attribution.withOrigin({kind:'navigation',name:'/growth',to:'/growth',initial:visit===0},()=>{});flush()};equal(list.filter(e=>e.code==='GRAPH_GROWTH').length,0);if(leak)add();OBSERVE?.attribution.withOrigin({kind:'navigation',name:'/growth',to:'/growth'},()=>{});flush()}finally{for(const stop of stops)stop()}}));const found=events.filter(e=>e.code==='GRAPH_GROWTH');equal(found.length,isDev&&leak?1:0);if(isDev&&leak){equal(found[0]!.data.route,'/growth');equal(found[0]!.data.history.length,3);ok(found[0]!.data.grew.includes('computations'));ok(found[0]!.data.roots>=1);ok(found[0]!.data.routes.includes('/growth'));equal(found[0]!.severity,'warn')}}
 })
 doc('fallback-flash-default',555,'Fallback displayed under150ms emits one info channel event; off disables reporting but not the fold count.',async()=>{
 for(const enabled of [false,true]){const target=document.createElement('div');document.body.appendChild(target);const gate=deferred<number>();let dispose!:()=>void;const events=await capture(async()=>{const release=attribution.enable({...quiet,fallbackFlashes:enabled});try{dispose=render(()=>{const n=createMemo(()=>gate.promise);return <Loading fallback='flash'><span>{n()}</span></Loading>},target);equal(target.textContent,'flash');await ticks(2);gate.resolve(1);await ticks(5);flush();equal(target.textContent,'1');if(isDev)ok(feedback().fallbacks.some(row=>row.flashes>=1))}finally{dispose();release();target.remove()}});const found=events.filter(e=>e.code==='FALLBACK_FLASH');equal(found.length,isDev&&enabled?1:0);if(isDev&&enabled){ok(found[0]!.data.shownMs<150);ok(found[0]!.ownerPath===undefined||Array.isArray(found[0]!.ownerPath))}}
 })
 doc('effect-relay-tear',494,'A derivable single-writer identity relay warns; direct derivation stays quiet.',async()=>{
 for(const relay of [false,true]){const events=await capture(()=>withEngine({},()=>{let close!:()=>void,write!:(n:number)=>void;createRoot(d=>{close=d;const[r,w]=createSignal(0,{name:'root'});write=w;const[copy,set]=createSignal(0,{name:'copy'});if(relay)createEffect(r,n=>{set(n)});const value=relay?copy:createMemo(r);createEffect(()=>r()+value(),()=>{})});try{flush();for(let i=1;i<=3;i++){write(i);flush()}}finally{close()}}));const found=events.filter(e=>e.code==='EFFECT_RELAY_TEAR');equal(found.length>0,isDev&&relay);if(isDev&&relay)ok(found.some(e=>e.severity==='warn'))}
 })
 doc('async-waterfall-tiers',463,'Depth2 is info channel-only; depth3 warns; all proven chains remain in history.',async()=>{for(const depth of [2,3]){const events=await capture(async()=>{const release=attribution.enable({...quiet,waterfalls:{minFlightMs:0}});let close!:()=>void;const first=deferred<number>();try{createRoot(d=>{close=d;const a=createMemo(()=>first.promise,{name:'first'});const b=createMemo(()=>{a();return Promise.resolve(2)},{name:'second'});const c=depth===3?createMemo(()=>{b();return Promise.resolve(3)},{name:'third'}):b;createEffect(c,()=>{})});flush();first.resolve(1);await ticks(12);flush();if(isDev)ok(attribution.history('waterfall').length>0)}finally{close();release()}});const found=events.filter(e=>e.code==='ASYNC_WATERFALL');if(isDev){ok(found.length>0);for(const event of found){equal(event.kind,'perf');equal(event.severity,event.data.chain.length>=3?'warn':'info');ok(event.data.chain.every((link:any)=>link.ms>=0));ok(event.data.sequentialMs>=0)}equal(found.some(e=>e.severity==='warn'),depth===3)}else equal(found,[])}})
 doc('checks-false',419,'checks:false folds off six cost checks, fanOut:false leaves only core threshold.',async()=>{const events=await capture(()=>withEngine({checks:false,hotRuns:{count:1,windowMs:1000},wideDeps:1,fanOut:1,unstableMemos:1,wastedRecompute:{budgetMs:0,minRuns:1,ratio:0,windowMs:1000}},()=>{let close!:()=>void,write!:(n:number)=>void;createRoot(d=>{close=d;const[r,w]=createSignal(0);write=w;createMemo(()=>({n:(r(),0)}));createMemo(r)});try{write(1);flush()}finally{close()}}));equal(events.filter(e=>['HOT_SCOPE_RERUNS','WIDE_SCOPE_DEPS','HUGE_FAN_OUT','UNSTABLE_MEMO_OUTPUT','WASTED_RECOMPUTE'].includes(e.code)),[])})
}
export const costDiagnosticCases=cases
