import { createRoot } from 'solid-js'
import {
	isServer, createRequestEvent, getRequestEvent, createResponseStub, createSSRResponse, commitEventResponse,
	renderToStream, renderToString, httpStatus, httpHeader, getTraceContext, composeMiddleware,
	parseCookieHeader, serializeCookie, redirect, reload, respond,
} from '@solidjs/web'
import { provideRequestEvent } from '@solidjs/web/storage'
import { equal, ok, throws, type DocCase } from './registry'
import { deferred } from '../../harness/timing'
const cases:DocCase[]=[]
function doc(name:string,statement:string,run:DocCase['run']){cases.push({id:`12/${name}`,file:'12-ssr-http.md',statement,run})}
function scope<T>(fn:()=>T,headers?:HeadersInit){const event=createRequestEvent(new Request('http://conformance.test/',{headers}));return provideRequestEvent(event,()=>fn())}

doc('cookie-roundtrip','Names and values travel percent-encoded and the parser decodes symmetrically.',()=>{const cookie=serializeCookie('na me','你好;=value');equal(parseCookieHeader(cookie.split(';')[0]!),{'na me':'你好;=value'})})
doc('cookie-default-path','path defaults to /, the only default.',()=>{const s=serializeCookie('a','b');ok(s.includes('Path=/'));ok(!s.includes('HttpOnly'));ok(!s.includes('Secure'))})
doc('cookie-options','domain/maxAge/expires/httpOnly/secure/sameSite are emitted exactly when given.',()=>{const s=serializeCookie('a','b',{domain:'example.test',maxAge:7,httpOnly:true,secure:true,sameSite:'lax'});for(const part of ['Domain=example.test','Max-Age=7','HttpOnly','Secure','SameSite=Lax'])ok(s.includes(part),s)})
doc('cookie-delete','Deleting is expiring: empty value plus Max-Age=0.',()=>ok(serializeCookie('a','',{maxAge:0}).includes('Max-Age=0')))
doc('client-http-noop','httpStatus and httpHeader are no-ops on the client.',()=>{if(isServer)return;httpStatus(404);httpHeader('x-test','value')})
if(isServer){
	doc('fresh-events','createRequestEvent builds request, locals and a fresh uncommitted response stub.',()=>{const request=new Request('http://conformance.test/');const a=createRequestEvent(request),b=createRequestEvent(request);equal(a.request===request,true);ok(a.locals!==b.locals);ok(a.response!==b.response);equal(a.response.committed,false)})
	doc('event-init','init spreads over defaults so a framework can extend the shape.',()=>{const locals={user:'a'};const e=createRequestEvent(new Request('http://conformance.test/'),{locals});equal(e.locals===locals,true)})
	doc('request-scope','getRequestEvent reads the current event anywhere under a request scope.',()=>scope(()=>{const event=getRequestEvent();ok(event);equal(event,getRequestEvent())}))
	doc('head-retraction','Each declaration snapshots the prior value and restores it when its owning scope is disposed.',()=>scope(()=>{const e=getRequestEvent()!;e.response.status=404;e.response.headers.set('x-scope','outer');const close=createRoot(dispose=>{httpStatus(500);httpHeader('x-scope','inner');return dispose});equal(e.response.status,500);equal(e.response.headers.get('x-scope'),'inner');close();equal(e.response.status,404);equal(e.response.headers.get('x-scope'),'outer')}))
	doc('head-committed-noop','Both declaration writes and retractions no-op once the head is committed.',()=>scope(()=>{const e=getRequestEvent()!;e.response.status=201;e.response.committed=true;createRoot(dispose=>{httpStatus(500);httpHeader('x-noop','ignored');dispose()});equal(e.response.status,201);equal(e.response.headers.get('x-noop'),null)}))
	doc('cookie-response-not-request','A Set-Cookie appended in the same request does not read back.',()=>scope(()=>{const e=getRequestEvent()!;e.response.headers.append('set-cookie','new=value');equal(parseCookieHeader(e.request.headers.get('cookie')), {})}))
	doc('ssr-response-string','String results return a Response synchronously and commit the stub.',()=>scope(()=>{const e=getRequestEvent()!;e.response.status=201;const response=createSSRResponse('<p>ok</p>',e);ok(response instanceof Response);equal(response.status,201);equal(e.response.committed,true);ok(response.headers.get('content-type')!.includes('text/html'))}))
	doc('ssr-response-cookies','Every materialized response carries Set-Cookie entry-by-entry.',()=>scope(()=>{const e=getRequestEvent()!;e.response.headers.append('set-cookie','a=1');e.response.headers.append('set-cookie','b=2');const response=createSSRResponse('body',e);equal(response.headers.getSetCookie(),['a=1','b=2'])}))
	doc('early-redirect','Location before shell flush produces a real bodyless redirect with cookies.',()=>scope(()=>{const e=getRequestEvent()!;e.response.status=404;e.response.headers.set('location','/next');e.response.headers.append('set-cookie','a=1');const response=createSSRResponse('body',e);equal(response.status,302);equal(response.body,null);equal(response.headers.get('location'),'/next');equal(response.headers.getSetCookie(),['a=1'])}))
	doc('stream-response-head','Stream results resolve at shell flush, with stub committed.',()=>scope(async()=>{const e=getRequestEvent()!;const result=renderToStream(()=><span>ok</span>);const response=await createSSRResponse(result,e);equal(e.response.committed,true);ok((await response.text()).includes('ok'))}))
	doc('aborted-before-shell','A render aborted before flush resolves to bodyless 500 and never rejects.',()=>scope(async()=>{const e=getRequestEvent()!;const controller=new AbortController();controller.abort();const result=renderToStream(()=><span>ok</span>,{signal:controller.signal,onError:()=>{}});const response=await createSSRResponse(result,e);equal(response.status,500);equal(response.body,null);equal(e.response.committed,true)}))
	doc('commit-other-status','commitEventResponse never takes status from the stub.',()=>scope(()=>{const e=getRequestEvent()!;e.response.status=500;e.response.headers.set('x-stub','a');const response=commitEventResponse(new Response('api',{status:201}),e);equal(response.status,201);equal(response.headers.get('x-stub'),'a');equal(e.response.committed,true)}))
	doc('commit-other-precedence','Response metadata wins; ordinary stub headers fill only gaps.',()=>scope(()=>{const e=getRequestEvent()!;e.response.headers.set('x-header','stub');const response=commitEventResponse(new Response('api',{headers:{'x-header':'response'}}),e);equal(response.headers.get('x-header'),'response')}))
	doc('commit-idempotent','An already-committed stub passes the response through untouched.',()=>scope(()=>{const e=getRequestEvent()!;const response=createSSRResponse('body',e);equal(commitEventResponse(response,e)===response,true)}))
	doc('commit-cookies','Stub cookies append beside response cookies entry-by-entry.',()=>scope(()=>{const e=getRequestEvent()!;e.response.headers.append('set-cookie','a=1');const response=commitEventResponse(new Response('body',{headers:{'set-cookie':'b=2'}}),e);equal(response.headers.getSetCookie(),['b=2','a=1'])}))
	doc('trace-continuation','getTraceContext continues a valid incoming traceparent and returns one object per request.',()=>scope(()=>{const trace=getTraceContext()!;equal(trace.traceId,'11111111111111111111111111111111');equal(trace.parentId,'2222222222222222');equal(trace.sampled,true);equal(trace===getTraceContext(),true)}, {traceparent:'00-11111111111111111111111111111111-2222222222222222-01'}))
	doc('trace-invalid','Malformed all-zero ids are ignored and a new trace originates.',()=>scope(()=>{const trace=getTraceContext()!;ok(trace.traceId!=='00000000000000000000000000000000');equal(trace.parentId,undefined)},{traceparent:'00-00000000000000000000000000000000-2222222222222222-01'}))
	doc('trace-unsampled-wire','An unsampled upstream trace stays off the browser wire.',()=>scope(()=>{const response=createSSRResponse('body',getRequestEvent()!);ok(!response.headers.get('server-timing')?.includes('traceparent'))},{traceparent:'00-11111111111111111111111111111111-2222222222222222-00'}))
	doc('trace-sampled-wire','Sampled trace entries are emitted as Server-Timing on commit.',()=>scope(()=>{const response=createSSRResponse('body',getRequestEvent()!);ok(response.headers.get('server-timing')?.includes('traceparent'))},{traceparent:'00-11111111111111111111111111111111-2222222222222222-01'}))
	doc('middleware-order','next advances the chain, and outermost middleware unwinds before the wire.',()=>scope(async()=>{const seen:string[]=[];const run=composeMiddleware([async(_req,next)=>{seen.push('a');const res=await next();seen.push('A');res.headers.set('x-after','yes');return res},async(_req,next)=>{seen.push('b');const res=await next();seen.push('B');return res}]);const res=await run(getRequestEvent()!.request,()=>{seen.push('terminal');return new Response('body')});equal(seen,['a','b','terminal','B','A']);equal(res.headers.get('x-after'),'yes')}))
	doc('middleware-request','next may substitute the Request downstream.',()=>scope(async()=>{const run=composeMiddleware([(_req,next)=>next(new Request('http://conformance.test/other'))]);let seen='';await run(getRequestEvent()!.request,request=>{seen=request!.url;return new Response('body')});equal(seen,'http://conformance.test/other')}))
}
export const httpCases=cases
