import {renderToFrameStream} from '@solidjs/web/frames/server'
import {OBSERVE,createMemo,Loading} from 'solid-js'
import {renderToString,createRequestEvent,RequestContext} from '@solidjs/web'
import {AsyncLocalStorage} from 'node:async_hooks'
import {registerServerReference,createServerReference,configureServerFunctionsServer} from '@solidjs/web/server-functions/server'
;(globalThis as any)[RequestContext]??=new AsyncLocalStorage()
export function policyObserver(){const rows:any[]=[];let first=0,second=0,errors=0;const nativeError=console.error;console.error=()=>{errors++};const off=OBSERVE?.records.subscribe('invocation',e=>{rows.push(e);return 999}),bad=OBSERVE?.records.subscribe('invocation',()=>{throw new Error('observer cannot alter policy')});const fn=createServerReference(registerServerReference('late-policy',()=>5));try{return(globalThis as any)[RequestContext].run(createRequestEvent(new Request('http://late.local/')),()=>{configureServerFunctionsServer({wrapInvocation:run=>{first++;return Number(run())+1}});const a=fn();configureServerFunctionsServer({wrapInvocation:run=>{second++;return Number(run())*3}});const b=fn();return{a,b,first,second,errors,rows}})}finally{off?.();bad?.();configureServerFunctionsServer({wrapInvocation:undefined});console.error=nativeError}}

export async function bareFrameClock(){const rows:any[]=[];const off=OBSERVE?.records.subscribe('frame',e=>rows.push(e));let clock=1000;const descriptor=Object.getOwnPropertyDescriptor(performance,'now');Object.defineProperty(performance,'now',{configurable:true,value:()=>clock});try{for(const id of ['named',undefined]){let resolve!:(s:string)=>void;const gate=new Promise<string>(r=>resolve=r);function Data(){const data=createMemo(()=>gate);return <b>{data()}</b>};const stream=renderToFrameStream(()=><Loading fallback="pending"><Data/></Loading>,{...(id?{frame:{id,version:1}}:{})});const done=Promise.resolve(stream);await new Promise(r=>setTimeout(r,0));clock+=100;resolve('ready');await done};await Promise.resolve(renderToFrameStream(()=>{throw new Error('no-shell')},{frame:{id:'no-shell',version:1},onError:()=>{}})).catch(()=>{});return rows}finally{off?.();if(descriptor)Object.defineProperty(performance,'now',descriptor);else delete(performance as any).now}}

export function initialRenderRoute(){const rows:any[]=[];const off=OBSERVE?.records.subscribe('render',e=>rows.push(e));const html=renderToString(()=>OBSERVE?OBSERVE.attribution.withOrigin({kind:'navigation',initial:true,name:'/users/:id',to:'/users/42',params:{id:'42'}},()=><p>initial-route</p>):<p>initial-route</p>);off?.();return{html,rows}}
