import {OBSERVE,createRoot,createSignal,createMemo,createEffect,createRenderEffect,getOwner,flush,Loading} from 'solid-js'
import {attribution,feedback} from 'solid-js/attribution'
import {render} from '@solidjs/web'
import {equal,ok,type DocCase} from './registry'
import {deferred,ticks} from '../../harness/timing'
const cases:DocCase[]=[];function doc(id:string,statement:string,run:DocCase['run']){cases.push({id:'08/late-final-'+id,file:'08-dev-diagnostics.md',statement,run})}
const options={log:false,checks:false,holds:false,longHolds:false,waterfalls:false,abandonedFlights:false,stackedHolds:false,graphGrowth:false,fallbackFlashes:false,optimisticReverts:false} as const
// L1129: verdicts are cached on the first judged node, marks replace on the same owner.
doc('exclude-cached-verdicts','L1129: last creation mark wins; marks changed after nodes run never change those nodes.',()=>{if(!OBSERVE)return;for(const mode of ['include-then-exclude','exclude-then-include','late-exclude','late-include']){const release=attribution.enable(options);let close!:()=>void,write!:(n:number)=>void;try{createRoot(d=>{close=d;const owner=getOwner()!;if(mode==='include-then-exclude'){OBSERVE!.include(owner);OBSERVE!.exclude(owner)}if(mode==='exclude-then-include'){OBSERVE!.exclude(owner);OBSERVE!.include(owner)}if(mode==='late-include')OBSERVE!.exclude(owner);const[r,w]=createSignal(0);write=w;createMemo(r,{name:'cached-verdict'});if(mode==='late-exclude')OBSERVE!.exclude(owner);if(mode==='late-include')OBSERVE!.include(owner)});write(1);flush();equal(attribution.history('rerun').length,mode==='exclude-then-include'||mode==='late-exclude'?1:0)}finally{close();release()}}})
// L1123.8: root causes need no memo id, every derived change does.
doc('derived-cause-node-ids','L1123: every memo change on a rerun cause chain has the stable nodeId of its producing memo.',()=>{if(!OBSERVE)return;const release=attribution.enable(options);let close!:()=>void,write!:(n:number)=>void;const rows:any[]=[];const off=OBSERVE.records.subscribe('rerun',e=>rows.push(e));try{createRoot(d=>{close=d;const[r,w]=createSignal(0,{name:'root-write'});write=w;const a=createMemo(()=>r()*2,{name:'first-derived'}),b=createMemo(()=>a()+1,{name:'second-derived'});createEffect(b,()=>{},{name:'consumer'})});flush();rows.length=0;write(1);flush();const ids=new Map(rows.map(e=>[e.nodeName,e.nodeId]));let checked=0;const walk=(cause:any)=>{if(ids.has(cause.name)){equal(cause.nodeId,ids.get(cause.name));checked++}for(const parent of cause.causes??[])walk(parent)};for(const e of rows)for(const cause of e.causes)walk(cause);ok(checked>=2,JSON.stringify(rows))}finally{off();close();release()}})
// L1123.5/L1197: real supersession and landing; names, timing, identity and folded census.
doc('flight-fields-and-fold','L1123/L1197: native flight records land or abandon, preserve their node/interaction and fold all per-source counts and durations.',async()=>{if(!OBSERVE)return;const release=attribution.enable(options),a=deferred<number>(),b=deferred<number>();let close!:()=>void,write!:(n:number)=>void;const rows:any[]=[];const off=OBSERVE.records.subscribe('flight',e=>rows.push(e));try{createRoot(d=>{close=d;const[r,w]=createSignal(0);write=w;const data=createMemo(()=>r()===0?0:r()===1?a.promise:b.promise,{name:'flight-source'});createRenderEffect(data,()=>{})});flush();OBSERVE.attribution.withInteraction({type:'click',target:'button#source'},()=>write(1));flush();await ticks(3);write(2);flush();await ticks(3);b.resolve(2);await ticks(8);a.resolve(1);await ticks(3);flush();equal(rows.map(r=>r.outcome).sort(),['abandoned','landed']);for(const row of rows){equal(row.nodeName,'flight-source');ok(Number.isInteger(row.nodeId));ok(Number.isFinite(row.at));ok(row.durationMs>=0)}equal(rows[0].nodeId,rows[1].nodeId);equal(rows.find(r=>r.outcome==='abandoned').interaction.target,'button#source');const table=feedback().flights.find(r=>r.source==='flight-source')!;equal(table.flights,2);equal(table.landed,1);equal(table.abandoned,1);equal(table.landedMs,rows.find(r=>r.outcome==='landed').durationMs);equal(table.worstMs,table.landedMs);let rejected=false;try{attribution.history('flight' as any)}catch(e){rejected=String(e).includes('unknown record type')};ok(rejected)}finally{a.resolve(1);b.resolve(2);off();close();release()}})
// L1123.6/L1198: boundary native lifecycle, at the visibility drain, not promise kickoff.
doc('fallback-fields-and-fold','L1123/L1198: Loading fallback records visible lifetime and feedback folds exact 149/150ms flash boundary.',async()=>{if(!OBSERVE)return;let clock=1000;const descriptor=Object.getOwnPropertyDescriptor(performance,'now');Object.defineProperty(performance,'now',{configurable:true,value:()=>clock});const release=attribution.enable(options),rows:any[]=[];const off=OBSERVE.records.subscribe('fallback',e=>rows.push(e));try{for(const ms of [149,150]){const gate=deferred<number>(),target=document.createElement('div');function FallbackFixture(){const data=createMemo(()=>gate.promise,{name:'fallback-data'});return <Loading fallback={<i>pending</i>}><b>{data()}</b></Loading>};const at=clock,close=render(()=><FallbackFixture/>,target);try{flush();await ticks(4);equal(target.textContent,'pending');clock+=ms;gate.resolve(1);await ticks(8);flush();equal(target.textContent,'1');const row=rows.at(-1);equal(row.at,at);equal(row.shownMs,ms);ok(row.ownerPath.includes('<FallbackFixture>'));equal(row.interaction,undefined)}finally{gate.resolve(1);close()}}equal(rows.length,2);const folded=feedback().fallbacks;equal(folded.length,2);equal(folded.map(r=>r.shows),[1,1]);equal(folded.reduce((n,r)=>n+r.shownMs,0),299);equal(folded.map(r=>r.worstMs),[149,150]);equal(folded.map(r=>r.flashes),[1,0]);ok(folded.every(r=>r.boundary.includes('FallbackFixture')))}finally{off();release();if(descriptor)Object.defineProperty(performance,'now',descriptor);else delete(performance as any).now}})
export const lateFinalCases=cases
