import {test,expect} from 'bun:test'
import {chromium} from 'playwright'
import {build,type BuildMode} from '../../scripts/build'
import {resolve} from 'node:path'
import {rm} from 'node:fs/promises'
test('08 L1220 native timeline labels colors clocks and all structured families',async()=>{const mode=(process.env.BUILD_MODE??'development') as BuildMode,dir=resolve('.build','late-native-'+process.pid);await build(dir,mode,{client:['tracks/docs/late-final-native-client.tsx'],server:[]});const server=Bun.serve({port:0,fetch:r=>new URL(r.url).pathname.endsWith('.js')?new Response(Bun.file(dir+new URL(r.url).pathname),{headers:{'content-type':'text/javascript'}}):new Response('<div id="root"></div><script type="module" src="/late-final-native-client.js"></script>',{headers:{'content-type':'text/html'}})}),browser=await chromium.launch({channel:'chrome',headless:true});try{const page=await browser.newPage();await page.goto(String(server.url));await page.waitForFunction(()=>!!(window as any).lateNative);const r=await page.evaluate(()=>(window as any).lateNative());await Bun.write('artifacts/late-native-'+mode+'.json',JSON.stringify(r,null,2));if(mode==='production'){expect(r.entries).toEqual([]);expect(r.rows).toEqual([]);return}const all=[...r.base.entries,...r.entries],props=(e:any)=>Object.fromEntries(e.detail.devtools.properties??[]);for(const e of all.filter((e:any)=>e.detail.devtools.dataType==='track-entry')){expect(e.detail.devtools.trackGroup).toBe('Solid');expect(e.start).toBeGreaterThanOrEqual(0);expect(e.duration).toBeGreaterThanOrEqual(0);expect(['primary','primary-light','primary-dark','secondary','secondary-light','secondary-dark','tertiary','warning','error']).toContain(e.detail.devtools.color)}const tracks=all.map((e:any)=>e.detail.devtools.track);for(const track of ['Interactions','Propagation','Effects','Memos','Async','Holds','Navigations'])expect(tracks).toContain(track)
 const find=(track:string,predicate:(e:any)=>boolean)=>{const value=all.find((e:any)=>e.detail.devtools.track===track&&predicate(e));expect(value).toBeDefined();return value}
 find('Interactions',e=>e.name==='input delay');find('Interactions',e=>e.name.startsWith('click on button#short')&&'Handler'in props(e));find('Interactions',e=>e.name==='held'&&e.detail.devtools.color==='warning')
 const wave=find('Propagation',e=>e.name.includes('native-short')&&e.name.includes('run')&&'Writes'in props(e));for(const key of ['Duration','Writes','Re-runs','Unchanged','Created','Held'])expect(props(wave)).toHaveProperty(key)
 find('Propagation',e=>e.name.includes('←')&&e.name.includes('equal-short'));for(const track of ['Effects','Memos']){find(track,e=>e.name.includes('· create'));find(track,e=>'Self time'in props(e)&&'Phase'in props(e))};find('Effects',e=>e.name.includes('· callback'));find('Memos',e=>e.detail.devtools.color==='warning'&&props(e).Changed==='no — unchanged (wasted)')
 const timedMemo=find('Memos',e=>e.name==='equal-short'&&props(e).Changed==='yes'&&props(e)['Self time']==='2.00ms');expect(timedMemo.detail.devtools.color).toBe('primary');for(const key of ['Run','Self time','Total time','Changed','Phase','Deps','Causes'])expect(props(timedMemo)).toHaveProperty(key);const timedCallback=find('Effects',e=>e.name==='paint-short · callback');expect(timedCallback.detail.devtools.color).toBe('secondary-light');expect(props(timedCallback).Duration).toBe('3.00ms');const drains=r.rows.filter((x:any)=>x.type==='flush');for(const x of r.rows.filter((x:any)=>x.type==='rerun')){const causeSpan=r.entries.find((e:any)=>e.detail.devtools.track==='Propagation'&&e.name.includes(' ←')&&props(e)['Node id']===String(x.event.nodeId)&&e.start===x.event.at);expect(causeSpan).toBeDefined();expect(causeSpan.duration).toBeCloseTo(x.event.totalMs,5);expect(drains.some((d:any)=>d.event.at<=causeSpan.start&&d.event.at+d.event.durationMs>=causeSpan.start+causeSpan.duration)).toBe(true)}
 const abandoned=find('Async',e=>e.name.includes('abandoned'));expect(abandoned.detail.devtools.color).toBe('warning');expect(props(abandoned).Outcome).toBe('abandoned');const flight=r.rows.find((x:any)=>x.type==='flight'&&x.event.outcome==='abandoned').event;expect(abandoned.start).toBe(flight.at);expect(abandoned.duration).toBeCloseTo(flight.durationMs,5)
 const fallback=find('Async',e=>e.name.startsWith('fallback')&&e.name.includes('NativeFallback'));expect(fallback.detail.devtools.color).toBe('tertiary');expect(props(fallback)).toHaveProperty('Shown')
 for(const [name,color] of [['short','warning'],['long','error']]){const held=find('Holds',e=>e.name.includes('remote-'+name));expect(held.detail.devtools.color).toBe(color);for(const key of ['Held','Tail','Flushes','Held writes','Acknowledged by','Painted during hold','Verdict'])expect(props(held)).toHaveProperty(key);const hold=r.rows.find((x:any)=>x.type==='hold'&&x.event.blockers.includes('remote-'+name)).event;expect(held.start).toBe(hold.at);expect(held.duration).toBeCloseTo(hold.holdMs,5)}
 const nav=find('Navigations',e=>e.name.includes('/native/short'));for(const key of ['Settled','Writes','To','Outcome'])expect(props(nav)).toHaveProperty(key)
 }finally{await browser.close();server.stop(true);await rm(dir,{recursive:true,force:true})}},60000)
