import {test,expect} from 'bun:test'
import {chromium} from 'playwright'
import {build} from '../../scripts/build'
import {deferred} from '../../harness/timing'
import {resolve} from 'node:path'
import {rm} from 'node:fs/promises'
// 08 L674: absent module URL warns, page survives without a preload and the
// genuine client module request occurs during hydration, controlled by transport.
test('unmapped lazy assets still render and request the component late in Chrome hydration',async()=>{const dir=resolve('.build','lazy-evidence-'+process.pid),mode=(process.env.BUILD_MODE??'development') as any;await build(dir,mode,{client:['tracks/docs/lazy-evidence-client.tsx','tracks/docs/late-part.tsx'],server:['tracks/docs/lazy-evidence-server.tsx']});const runtime=await import(dir+'/lazy-evidence-server.js'),rendered=await runtime.page();expect(rendered.events.length).toBe(rendered.dev?1:0);if(rendered.dev)expect(rendered.events[0]).toEqual({kind:'ssr',severity:'warn',data:{reason:'no-module-url'}});expect(rendered.html).toContain('ready');expect(rendered.html).not.toContain('rel="modulepreload"');const gate=deferred<void>();let calls=0;const server=Bun.serve({port:0,fetch:async r=>{const path=new URL(r.url).pathname;if(path==='/late-part.js'){calls++;await gate.promise};return path.endsWith('.js')?new Response(Bun.file(dir+path),{headers:{'content-type':'text/javascript'}}):new Response(rendered.html+'<script type="module" src="/lazy-evidence-client.js"></script>',{headers:{'content-type':'text/html'}})}});const browser=await chromium.launch({channel:'chrome',headless:true});try{const page=await browser.newPage();const errors:string[]=[];page.on('pageerror',e=>errors.push(String(e)));await page.goto(server.url.toString(),{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>!!(window as any).lazyEvidence);expect(await page.evaluate(()=>(window as any).lazyEvidence.inspect().started)).toBe(true);expect(await page.evaluate(()=>(window as any).lazyEvidence.inspect().completed)).toBe(false);expect(calls).toBe(1);gate.resolve();await page.waitForFunction(()=>(window as any).lazyEvidence.inspect().completed);expect(await page.evaluate(()=>(window as any).lazyEvidence.inspect().text)).toBe('ready');expect(errors).toEqual([]);await page.evaluate(()=>(window as any).lazyEvidence.stop())}finally{gate.resolve();await browser.close();server.stop(true);await rm(dir,{recursive:true,force:true})}},30000)
