import {OBSERVE,createRoot,createComponent,createSignal,createStore,createOptimisticStore,createMemo,createEffect,createTrackedEffect,flush,untrack,onSettled,onCleanup,refresh,affects,Loading,For,Show,Switch,Match} from 'solid-js'
import {isServer,isDev,render} from '@solidjs/web'
import {resetErrorHalt} from '@solidjs/signals'
import {equal,ok,type DocCase} from './registry'
import {ticks,deferred} from '../../harness/timing'
const cases:DocCase[]=[]
function doc(id:string,run:DocCase['run']){cases.push({id:'08/primitive-'+id,file:'08-dev-diagnostics.md',statement:({'owned-write-scopes':'L35: Writing reactive state inside effect compute/memo/component throws; ownedWrite explicitly opts in.','async-setter-families':'L57: Store-family async setters commit synchronous writes then dev throws; later writes land on closed draft.','signal-promise-valid':'L57: A signal may legitimately hold a promise.','strict-read-contexts':'L307: Component signal/props/store top-level reads capture once without updating.','pending-forbidden-both':'L365: Pending reads in trackedEffect/onSettled throw rather than route Loading.','leaf-owner-families':'L199: Leaf scopes forbid computations; static signal exception is finding010.','sync-node-async-kinds':'L267: Sync nodes reject promises/thenables/async iterables in dev and hold their raw value in production.','affects-extra-key':'L279: Additional keys are not a path.','root-async-mount':'L105–107: Initial render defers root attach until uncaught async settles; existing shell stays meanwhile.','root-sync-mount':'L105: No-async render attaches synchronously.','halt-lifecycle':'L291: Uncaught render failure halts scheduler, emits once, reportError sees cause, first subsequent write is ignored.','strict-component-controls':'01:L45; 08:L307: signal/props/store component reads warn; untrack/memo/effect tracking controls remain quiet.','strict-flow-callback-controls':'01:L64: For/Show/Match callback top-level accessor reads do not track; memo/effect/untrack controls.','effect-backhalf-store-proxy':'01:L176;04:L215: Effect back-half store-proxy reads warn and never become dependencies.'} as Record<string,string>)[id]??id,run})}
async function observe(run:()=>unknown|Promise<unknown>){const session=OBSERVE?.diagnostics.capture(),warn=console.warn,error=console.error;const printed:string[]=[];console.warn=console.error=(...args)=>printed.push(String(args[0]));try{await run();await ticks(3);return {events:[...(session?.events??[])],printed}}finally{session?.stop();console.warn=warn;console.error=error}}
function root(fn:()=>void){let dispose!:()=>void;createRoot(d=>{dispose=d;fn()});return dispose}
function code(result:Awaited<ReturnType<typeof observe>>,name:string,count:number){equal(result.events.filter(e=>e.code===name).length,isDev?count:0)}
if(!isServer){
 doc('owned-write-scopes',async()=>{for(const scope of ['component','memo','effect'] as const){for(const intentional of [false,true]){let dispose!:()=>void,caught:unknown;const r=await observe(()=>{try{dispose=root(()=>{const[,write]=createSignal(0,{ownedWrite:intentional});const perform=()=>write(1);if(scope==='component')createComponent(()=>{perform();return null},{});else if(scope==='memo')untrack(createMemo(perform));else createEffect(perform,()=>{});flush()})}catch(e){caught=e}finally{dispose?.();resetErrorHalt()}});code(r,'REACTIVE_WRITE_IN_OWNED_SCOPE',intentional?0:1);if(scope!=='effect')equal(!!caught,isDev&&!intentional)}}})
 doc('async-setter-families',async()=>{for(const family of ['store','optimistic','derived'] as const){let read!:any,write!:any;const gate=deferred<void>();let completion!:Promise<void>,caught:unknown;const close=root(()=>{[read,write]=family==='store'?createStore({n:0}):family==='optimistic'?createOptimisticStore({n:0}):createStore(()=>({n:0}),{n:0})});try{const r=await observe(()=>{try{write((draft:any)=>{completion=(async()=>{draft.n=1;await gate.promise;draft.n=2})();return completion})}catch(e){caught=e}});code(r,'ASYNC_STORE_SETTER',1);equal(!!caught,isDev);flush();equal(untrack(()=>read.n),family==='optimistic'?0:1);gate.resolve();await completion;flush();equal(untrack(()=>read.n),family==='optimistic'?0:1)}finally{gate.resolve();close()}}})
 doc('signal-promise-valid',async()=>{const value=Promise.resolve(1);let read!:()=>unknown,write!:(v:unknown)=>void;const close=root(()=>{[read,write]=createSignal<unknown>(0)});try{const r=await observe(()=>{write(value);flush();equal(untrack(read),value)});code(r,'ASYNC_STORE_SETTER',0)}finally{close()}})
 doc('strict-read-contexts',async()=>{for(const shape of ['signal','store','props'] as const){let write!:()=>void,first=0,runs=0,dispose!:()=>void;const r=await observe(()=>{dispose=root(()=>{const [read,set]=createSignal(1);const [store,setStore]=createStore({n:1});write=()=>{set(2);setStore(d=>{d.n=2});flush()};function View(props:{n:number}){runs++;first=shape==='signal'?read():shape==='store'?store.n:props.n;return null}createComponent(View,{get n(){return read()}});flush()});write();equal(first,1);equal(runs,1);dispose()});code(r,'STRICT_READ_UNTRACKED',1)}})
 doc('pending-forbidden-both',async()=>{for(const family of ['tracked','settled'] as const){let caught:unknown,dispose!:()=>void;const r=await observe(()=>{dispose=root(()=>{const read=createMemo(()=>new Promise<number>(()=>{}));const body=()=>{try{read()}catch(e){caught=e}};if(family==='tracked')createTrackedEffect(body);else onSettled(body);flush()});dispose()});ok(caught);code(r,'PENDING_ASYNC_FORBIDDEN_SCOPE',1)}})
 doc('leaf-owner-families',async()=>{for(const scope of ['tracked','settled'] as const){for(const kind of ['signal','memo','effect'] as const){let caught:unknown,dispose!:()=>void;const r=await observe(()=>{dispose=root(()=>{const body=()=>{try{if(kind==='signal')createSignal(0);else if(kind==='memo')createMemo(()=>0);else createEffect(()=>0,()=>{})}catch(e){caught=e}};scope==='tracked'?createTrackedEffect(body):onSettled(body);flush()});dispose()});code(r,'PRIMITIVE_IN_FORBIDDEN_SCOPE',kind==='signal'?0:1);equal(!!caught,isDev&&kind!=='signal')}}})
 doc('sync-node-async-kinds',async()=>{for(const value of [Promise.resolve(1),{then(resolve:(v:number)=>void){resolve(2)}},{async *[Symbol.asyncIterator](){yield 3}}]){let read!:()=>unknown,caught:unknown,dispose!:()=>void;const r=await observe(()=>{try{dispose=root(()=>{read=createMemo(()=>value,{sync:true});untrack(read)})}catch(e){caught=e}finally{dispose?.()}});code(r,'SYNC_NODE_RECEIVED_ASYNC',1);equal(!!caught,isDev);if(!isDev)equal(untrack(read),value)}})
 doc('affects-extra-key',async()=>{const close=root(()=>{});try{const r=await observe(()=>{let caught:unknown;try{(affects as any)({},'x','y')}catch(e){caught=e};equal(!!caught,isDev)});code(r,'INVALID_AFFECTS_TARGET',1)}finally{close()}})
 doc('root-async-mount',async()=>{for(const wrapped of [false,true]){const gate=deferred<string>();const target=document.createElement('div');target.textContent='shell';document.body.appendChild(target);let dispose!:()=>void;const r=await observe(async()=>{dispose=render(()=>{const read=createMemo(()=>gate.promise);return wrapped?<Loading fallback='pending'><span>{read()}</span></Loading>:<span>{read()}</span>},target);equal(target.textContent,wrapped?'shellpending':'shell');gate.resolve('ready');await ticks(8);flush();equal(target.textContent,'shellready');dispose();target.remove()});code(r,'ASYNC_OUTSIDE_LOADING_BOUNDARY',wrapped?0:1)}})
 doc('root-sync-mount',()=>{const target=document.createElement('div');const close=render(()=><span>synchronous</span>,target);equal(target.textContent,'synchronous');close()})
 doc('strict-component-controls',async()=>{for(const shape of ['signal','store','props'] as const){for(const mode of ['direct','untrack','memo','effect'] as const){let close!:()=>void,write!:()=>void,get!:()=>number;const result=await observe(()=>{close=root(()=>{const [read,set]=createSignal(1);const [store,setStore]=createStore({n:1});write=()=>{set(2);setStore(d=>{d.n=2});flush()};createComponent((props:{n:number})=>{const reader=()=>shape==='signal'?read():shape==='store'?store.n:props.n;if(mode==='direct'){const n=reader();get=()=>n}else if(mode==='untrack'){const n=untrack(reader);get=()=>n}else if(mode==='memo')get=createMemo(reader);else{let n=0;createEffect(reader,v=>{n=v});get=()=>n}return null},{get n(){return read()}});flush()});equal(untrack(get),1);write();equal(untrack(get),mode==='memo'||mode==='effect'?2:1);close()});code(result,'STRICT_READ_UNTRACKED',mode==='direct'?1:0)}}})
 doc('strict-flow-callback-controls',async()=>{for(const shape of ['for','show','match'] as const){for(const mode of ['direct','untrack','memo','effect'] as const){const target=document.createElement('div');document.body.appendChild(target);let write!:(n:number)=>void,dispose!:()=>void;const applied:number[]=[];const result=await observe(()=>{dispose=render(()=>{const [read,set]=createSignal(1);write=set;const fill=(reader:()=>number)=>{if(mode==='memo'){const v=createMemo(reader);return <span>{v()}</span>}if(mode==='effect'){createEffect(reader,n=>{applied.push(n)});return <span>effect</span>}const n=mode==='direct'?reader():untrack(reader);return <span>{n}</span>};return shape==='for'?<For each={[read()]} keyed={false}>{(item)=>fill(item)}</For>:shape==='show'?<Show when={read()}>{v=>fill(v)}</Show>:<Switch><Match when={read()}>{v=>fill(v)}</Match></Switch>},target);flush();equal(target.textContent,mode==='effect'?'effect':'1');write(2);flush();ok(target.textContent===(mode==='effect'?'effect':mode==='memo'?'2':'1'),shape+'/'+mode+': '+target.textContent);if(mode==='effect')equal(applied,[1,2]);dispose();target.remove()});equal(result.events.some(e=>e.code==='STRICT_READ_UNTRACKED'),isDev&&mode==='direct')}}})
 doc('effect-backhalf-store-proxy',async()=>{for(const intended of [false,true]){let dispose!:()=>void,setStore!:(v:number)=>void,runs=0,value=0;const result=await observe(()=>{dispose=root(()=>{const [state,write]=createStore({n:1});setStore=n=>write(d=>{d.n=n});createEffect(()=>0,()=>{runs++;value=intended?untrack(()=>state.n):state.n});flush()});equal(runs,1);equal(value,1);setStore(2);flush();equal(runs,1);equal(value,1);dispose()});code(result,'STRICT_READ_UNTRACKED',intended?0:1)}})
 doc('halt-lifecycle',async()=>{let write!:(v:number)=>void,dispose!:()=>void;const errors:unknown[]=[],host=globalThis as any,original=host.reportError;const target=document.createElement('div');document.body.appendChild(target);host.reportError=(e:unknown)=>errors.push(e);try{const r=await observe(async()=>{dispose=render(()=>{const [read,set]=createSignal(0);write=set;return <span>{(()=>{if(read())throw new Error('halt-test');return 0})()}</span>},target);equal(target.textContent,'0');write(1);try{flush()}catch{}await ticks(3);write(2);write(3);flush();equal(target.textContent,'0')});code(r,'REACTIVITY_HALTED',1);equal(r.printed.filter(v=>v.includes('[REACTIVITY_HALTED]')&&!v.includes('repair guide')&&!v.includes('Update ignored')).length,isDev?1:2);equal(r.printed.filter(v=>v.includes('Update ignored')).length,isDev?1:0);equal(errors.length,1);equal(String(errors[0]),'Error: halt-test')}finally{resetErrorHalt();dispose?.();target.remove();host.reportError=original}})
}
export const primitiveDiagnosticCases=cases
