import { createRoot, createSignal, createMemo, createEffect, createRenderEffect, createTrackedEffect, createStore, flush, untrack, onCleanup, merge, omit, snapshot, resolve } from 'solid-js'
import { equal, type DocCase } from './registry'
import { ticks } from '../../harness/timing'
const cases:DocCase[]=[]
function doc(chapter:string,name:string,statement:string,run:DocCase['run']){const files:Record<string,string>={'01':'01-reactivity-batching-effects.md','02':'02-signals-derived-ownership.md','04':'04-stores.md'};cases.push({id:chapter+'/'+name,file:files[chapter]!,statement,run})}
async function root<T>(setup:()=>T,check:(state:T)=>unknown|Promise<unknown>){let dispose!:()=>void;const state=createRoot(d=>{dispose=d;return setup()});try{await check(state)}finally{dispose();await ticks(2)}}
doc('01','lazy-dependencies','Lazy memos track dependencies normally once evaluated.',()=>root(()=>{const [read,write]=createSignal(1);const memo=createMemo(()=>read()*2,{lazy:true});const seen:number[]=[];createEffect(memo,v=>{seen.push(v)});return {write,seen}},s=>{flush();s.write(2);flush();equal(s.seen,[2,4])}))
doc('01','lazy-disposal','A lazy memo is torn down when its last subscriber disappears and recomputed from scratch on its next read.',()=>root(()=>{let runs=0,cleanups=0;const memo=createMemo(()=>{runs++;onCleanup(()=>{cleanups++});return runs},{lazy:true});let close!:()=>void;createRoot(d=>{close=d;createEffect(memo,()=>{})});return {memo,close,runs:()=>runs,cleanups:()=>cleanups}},s=>{flush();equal(s.runs(),1);s.close();equal(s.cleanups(),1);equal(untrack(s.memo),2)}))
doc('01','eager-idle-cache','A non-lazy owned memo lives for its owner lifetime and keeps its cached value when unsubscribed.',()=>root(()=>{let runs=0;const memo=createMemo(()=>++runs);return {memo,runs:()=>runs}},s=>{equal(untrack(s.memo),1);equal(untrack(s.memo),1);equal(s.runs(),1)}))
doc('01','memo-previous','Memo compute receives the previous result and options are its second argument.',()=>root(()=>{const [read,write]=createSignal(1);const seen:unknown[]=[];const memo=createMemo<number>((previous=0)=>{seen.push(previous);return previous+read()},{equals:false});createEffect(memo,()=>{});return {memo,write,seen}},s=>{flush();s.write(2);flush();equal(s.seen,[0,1]);equal(untrack(s.memo),3)}))
doc('01','back-half-untracked','Effect callbacks do not track reactive values read in the apply phase.',()=>root(()=>{const [a,setA]=createSignal(1),[b,setB]=createSignal(2);const seen:number[]=[];createEffect(a,value=>{seen.push(value+untrack(b))});return {setA,setB,seen}},s=>{flush();s.setB(5);flush();equal(s.seen,[3]);s.setA(2);flush();equal(s.seen,[3,7])}))
doc('01','tracked-effect-cleanup','A tracked effect returns a cleanup function, which runs before rerun and on disposal.',async()=>{const seen:string[]=[];await root(()=>{const [read,write]=createSignal(0);createTrackedEffect(()=>{const value=read();seen.push('run'+value);return()=>{seen.push('clean'+value)}});return write},write=>{flush();write(1);flush();equal(seen,['run0','clean0','run1'])});equal(seen,['run0','clean0','run1','clean1'])})
doc('01','render-effect-cleanup','Render effects accept split compute/apply handlers with cleanup on rerun and disposal.',async()=>{const seen:string[]=[];await root(()=>{const [read,write]=createSignal(0);createRenderEffect(read,value=>{seen.push('run'+value);return()=>{seen.push('clean'+value)}});return write},write=>{equal(seen,['run0']);write(1);flush();equal(seen,['run0','clean0','run1'])});equal(seen,['run0','clean0','run1','clean1'])})
doc('02','signal-function-value','To store a function as a value, wrap it in a function-returning initializer and updater.',()=>root(()=>{const fn=()=>1;const [read,write]=createSignal(()=>fn);return {fn,read,write}},s=>{equal(untrack(s.read),s.fn);const next=()=>2;s.write(()=>next);flush();equal(untrack(s.read),next)}))
doc('02','memo-equality','Default strict equality suppresses notifications; equals false allows identical outputs to notify.',()=>root(()=>{const [read,write]=createSignal(0);const object={};const same=createMemo(()=>{read();return object});const always=createMemo(()=>{read();return object},{equals:false});const log:string[]=[];createEffect(same,()=>{log.push('same')});createEffect(always,()=>{log.push('always')});return {write,log}},s=>{flush();s.log.length=0;s.write(1);flush();equal(s.log,['always'])}))
doc('04','merge-reactive-getters','merge is a reactive view, later sources take precedence, and source getters remain reactive.',()=>root(()=>{const [read,write]=createSignal(1);const v=merge({a:9,b:2},{get a(){return read()}});const seen:number[]=[];createEffect(()=>v.a,a=>{seen.push(a)});return {v,write,seen}},s=>{flush();equal(s.v.b,2);s.write(3);flush();equal(s.seen,[1,3])}))
doc('04','omit-reactive-getters','omit is a reactive view preserving unexcluded getters.',()=>root(()=>{const [read,write]=createSignal(1);const v=omit({get a(){return read()},b:2},'b');const seen:number[]=[];createEffect(()=>v.a,a=>{seen.push(a)});return {v,write,seen}},s=>{flush();s.write(3);flush();equal(s.seen,[1,3]);equal('b' in s.v,false)}))
doc('04','undefined-and-delete','Draft undefined stores a value; delete removes the property.',()=>root(()=>createStore<{a?:number,b?:number}>({a:1,b:2}),([store,set])=>{set(d=>{d.a=undefined;delete d.b});flush();equal(Object.keys(store),['a']);equal(snapshot(store),{a:undefined})}))
doc('04','promise-derived-store','A derived store compute can return a Promise and adopts its resulting record.',()=>root(()=>{const [store]=createStore(()=>Promise.resolve({n:2}),{n:0});return store},async store=>{await resolve(()=>store.n);equal(snapshot(store),{n:2})}))
export const remainingCoreCases=cases
