import { createSignal, flush, getOwner, onCleanup, createComponent, createStore, For, Reveal, Loading, createMemo, Show, Switch, Match } from 'solid-js'
import { render, renderToString, isServer, isDev, dynamic } from '@solidjs/web'
import { deferred, ticks } from '../../harness/timing'
import { equal, ok, type DocCase } from './registry'
const cases:DocCase[]=[]
function doc(chapter:string,name:string,statement:string,run:DocCase['run']){const files:Record<string,string>={'02':'02-signals-derived-ownership.md','03':'03-control-flow.md','07':'07-dom.md','04':'04-stores.md'};cases.push({id:chapter+'/'+name,file:files[chapter]!,statement,run})}
async function dom(App:()=>any,check:(el:HTMLDivElement)=>unknown|Promise<unknown>){const el=document.createElement('div');document.body.append(el);let close=()=>{};try{close=render(App,el);await ticks(2);await check(el)}finally{close();el.remove();await ticks(2)}}
if(!isServer){
 doc('04','shallow-for-keyed-replacement','Shallow rows with custom keying reuse DOM for same-key replacements and dispose or create changed keys.',async()=>{let set!:(fn:(draft:{id:number,n:number}[])=>void)=>void,created=0,disposed=0;await dom(()=>{const [rows,write]=createStore([{id:1,n:1},{id:2,n:2}],{shallow:true});set=write;return<For each={[...rows]} keyed={row=>row.id}>{row=>{created++;onCleanup(()=>{disposed++});return<span>{row().n}</span>}}</For>},el=>{const first=el.children[0];set(d=>{d[0]={id:1,n:3}});flush();equal(el.children[0],first);equal(el.textContent,'32');equal(created,2);set(d=>{d.splice(1,1,{id:3,n:4})});flush();equal(el.textContent,'34');equal(created,3);equal(disposed,1)})})
 for(const outer of ['sequential','together','natural'] as const)for(const inner of ['sequential','together','natural'] as const){
  doc('03',`reveal-matrix-${outer}-${inner}`,`A nested ${inner} Reveal is one composite slot under outer ${outer}; minimal readiness, parent holds and inner ordering follow the documented matrix.`,async()=>{
   for(const reversed of [false,true]){const gates=Array.from({length:4},()=>deferred<number>());await dom(()=>{const values=gates.map(gate=>createMemo(()=>gate.promise));const slot=(n:number)=><Loading fallback={<b>{'f'+n}</b>}><span>{values[n]!()}</span></Loading>;return<Reveal order={outer}>{slot(0)}<Reveal order={inner}>{slot(1)}{slot(2)}</Reveal>{slot(3)}</Reveal>},async el=>{
    equal(el.textContent,'f0f1f2f3')
    const land=async(n:number)=>{gates[n]!.resolve(n);await ticks(8)}
    if(!reversed){await land(0);equal(el.textContent,outer==='together'?'f0f1f2f3':'0f1f2f3');await land(1);const inside=inner==='together'?'f1f2':'1f2';equal(el.textContent,outer==='together'?'f0f1f2f3':'0'+inside+'f3');await land(3);equal(el.textContent,outer==='together'?(inner==='together'?'f0f1f2f3':'01f23'):outer==='sequential'?'0'+inside+'f3':'0'+inside+'3');await land(2)}
    else{await land(2);equal(el.textContent,outer==='natural'&&inner==='natural'?'f0f12f3':'f0f1f2f3');await land(1);equal(el.textContent,outer==='natural'?'f012f3':'f0f1f2f3');await land(0);equal(el.textContent,outer==='together'?'f0f1f2f3':'012f3');await land(3)}
    equal(el.textContent,'0123')
   })}
  })
 }
 doc('07','attribute-lowercase','Built-in attributes are lowercase attributes, while dynamic values are applied reactively.',async()=>{let write!:(v:string)=>void;await dom(()=>{const [value,set]=createSignal('a');write=set;return <div data-state={value()} tabindex={2}/>},el=>{const div=el.firstElementChild!;equal(div.getAttribute('tabindex'),'2');equal(div.getAttribute('data-state'),'a');write('b');flush();equal(div.getAttribute('data-state'),'b')})})
 doc('07','native-property-defaults','Input values, checked state and their default values preserve the stateful DOM property semantics.',()=>dom(()=><><input value="live" defaultValue="initial"/><input type="checkbox" checked={true} defaultChecked={false}/><textarea value="live" defaultValue="initial"/></>,el=>{const input=el.children[0] as HTMLInputElement,check=el.children[1] as HTMLInputElement,area=el.children[2] as HTMLTextAreaElement;equal(input.value,'live');equal(input.defaultValue,'initial');equal(check.checked,true);equal(check.defaultChecked,false);equal(area.value,'live');equal(area.defaultValue,'initial')}))
 doc('07','svg-mathml-namespaces','Recognized SVG and MathML elements receive their platform namespaces.',()=>dom(()=><><svg><circle cx="1"/></svg><math><mi>x</mi></math></>,el=>{equal(el.querySelector('circle')!.namespaceURI,'http://www.w3.org/2000/svg');equal(el.querySelector('mi')!.namespaceURI,'http://www.w3.org/1998/Math/MathML')}))
 doc('07','ref-unowned','Ref callbacks run without a reactive owner; directive setup is owned and cleanup belongs to the setup.',async()=>{let applied:ReturnType<typeof getOwner>|undefined,setup:ReturnType<typeof getOwner>|undefined,cleaned=false;await dom(()=>{function directive(){setup=getOwner();onCleanup(()=>{cleaned=true});return(el:HTMLElement)=>{applied=getOwner();el.dataset.applied='yes'}}return<div ref={directive()}/>},el=>{ok(setup);equal(applied,null);equal(el.firstElementChild!.getAttribute('data-applied'),'yes');equal(cleaned,false)});equal(cleaned,true)})
 doc('07','ref-bare-variable','A single bare-variable ref is assigned; a variable contained in an array is an ordinary value and is never assigned.',()=>{let single:HTMLDivElement|undefined,array:HTMLDivElement|undefined;return dom(()=><><div ref={single}/><div ref={[array]}/></>,el=>{equal(single,el.children[0]);equal(array,undefined)})})
 doc('07','native-event-options','Ref callbacks may install native event listeners with once and capture options.',()=>{let hits=0;return dom(()=><button ref={el=>el.addEventListener('click',()=>{hits++},{once:true,capture:true})}/>,el=>{const button=el.firstElementChild as HTMLButtonElement;button.click();button.click();equal(hits,1)})})
 doc('07','nested-root-propagation','A nested root event stopPropagation prevents outer root handlers from observing the native event.',async()=>{const hits:string[]=[];await dom(()=><div onClick={()=>{hits.push('outer')}}><section/></div>,el=>{const container=el.querySelector('section')!;const close=render(()=><button onClick={event=>{hits.push('inner');event.stopPropagation()}}>click</button>,container);try{container.querySelector('button')!.click();equal(hits,['inner'])}finally{close()}})})
 doc('07','reactive-class-style','Reactive class object composition and style objects update attributes in place.',async()=>{let write!:(v:boolean)=>void;await dom(()=>{const [active,set]=createSignal(false);write=set;return<div class={['base',{active:active()}]} style={{color:active()?'red':'blue'}}/>},el=>{const div=el.firstElementChild as HTMLDivElement;equal(div.className,'base');equal(div.style.color,'blue');write(true);flush();equal(div.className,'base active');equal(div.style.color,'red')})})
 doc('03','show-keyed-lifetime','Keyed Show remounts its branch when a truthy value identity changes; non-keyed Show preserves the branch.',async()=>{for(const keyed of [false,true]){let write!:(v:{n:number}|undefined)=>void,mounts=0,cleanups=0;function Child(){mounts++;onCleanup(()=>{cleanups++});return<span>child</span>}await dom(()=>{const [value,set]=createSignal<{n:number}|undefined>({n:1});write=set;return keyed?<Show when={value()} keyed>{_value=> <Child/>}</Show>:<Show when={value()}>{_value=> <Child/>}</Show>},el=>{const first=el.querySelector('span');write({n:2});flush();equal(mounts,keyed?2:1);equal(el.querySelector('span')===first,!keyed);write(undefined);flush();equal(cleanups,keyed?2:1);equal(el.querySelector('span'),null)})}})
 doc('03','match-keyed-lifetime','The active non-keyed Match updates its narrowed accessor without remounting its child.',async()=>{let write!:(v:{n:number})=>void,mounts=0;await dom(()=>{const [value,set]=createSignal({n:1});write=set;return<Switch><Match when={value()}>{v=>{mounts++;return<span>{v().n}</span>}}</Match></Switch>},el=>{const first=el.querySelector('span');write({n:2});flush();equal(el.textContent,'2');equal(mounts,1);equal(el.querySelector('span'),first)})})
 doc('03','dynamic-stable-shared','A dynamic factory is a stable Component and shares its source evaluation across mounted instances.',async()=>{let write!:(v:boolean)=>void,runs=0;await dom(()=>{const [multiline,set]=createSignal(false);write=set;const Tag=dynamic(()=>{runs++;return multiline()?'textarea':'input'});return<><Tag/><Tag/></>},el=>{equal(el.querySelectorAll('input').length,2);equal(runs,1);write(true);flush();equal(el.querySelectorAll('textarea').length,2);equal(runs,2)})})
 doc('02','component-cleanup-order','Parent cleanup registered before children unwinds after them in dev and production.',async()=>{const seen:string[]=[];function Child(){onCleanup(()=>{seen.push('child')});return<span/>}function Parent(){onCleanup(()=>{seen.push('parent')});return<Child/>}await dom(()=><Parent/>,()=>{});equal(seen,['child','parent'])})
 doc('02','component-cleanup-late','A parent cleanup registered after a child runs before it in production and after it in development.',async()=>{const seen:string[]=[];function Child(){onCleanup(()=>{seen.push('child')});return<span/>}function Parent(){const child=<Child/>;onCleanup(()=>{seen.push('parent')});return child}await dom(()=><Parent/>,()=>{});equal(seen,isDev?['child','parent']:['parent','child'])})
}
if(isServer){doc('07','input-ssr-default','SSR uses defaultValue for initial form markup, and value when no defaultValue is provided.',()=>{const html=renderToString(()=><><input value="live" defaultValue="initial"/><input value="live"/><textarea value="live" defaultValue="initial"/></>);ok(html.includes('value="initial"'));ok(html.includes('value="live"'));ok(html.includes('>initial</textarea>'))})}
export const remainingRenderCases=cases
