import { createMemo, Loading, createRoot } from 'solid-js'
import { isServer, isDev, RequestContext, createRequestEvent, getRequestEvent, createResponseStub, renderToStream, renderToString, createSSRResponse, commitEventResponse, getExpectedRedirectStatus, parseCookieHeader, serializeCookie, httpHeader, httpStatus } from '@solidjs/web'
import { provideRequestEvent } from '@solidjs/web/storage'
import { equal, ok, type DocCase } from './registry'
import { deferred } from '../../harness/timing'
const cases:DocCase[]=[]
function doc(name:string,statement:string,run:DocCase['run']){cases.push({id:'12/'+name,file:'12-ssr-http.md',statement,run})}
doc('cookie-proto-key','Any valid cookie name round-trips, including __proto__.',()=>{const value=parseCookieHeader(serializeCookie('__proto__','x').split(';')[0]!);equal(Object.hasOwn(value,'__proto__'),true);equal(value['__proto__'],'x')})
if(isServer){
 doc('event-outside-scope','getRequestEvent returns undefined outside a request scope.',()=>{const storage=(globalThis as unknown as Record<symbol,{exit<T>(callback:()=>T):T}>)[RequestContext]!;return storage.exit(()=>equal(getRequestEvent(),undefined))})
 doc('cookie-expiry-serialization','expires emits exactly the explicitly supplied date, and valid unusual cookie names round-trip.',()=>{const date=new Date('2030-01-01T00:00:00Z');ok(serializeCookie('a','b',{expires:date}).includes('Expires=Tue, 01 Jan 2030 00:00:00 GMT'));for(const name of ['constructor','name space','name;=']){const header=serializeCookie(name,'x');const parsed=parseCookieHeader(header.split(';')[0]!);equal(Object.hasOwn(parsed,name),true);equal(parsed[name],'x')}})
 doc('cookie-scope-independent','Native Headers cookie appends remain after a reactive owner is disposed and preserve separate entries.',()=>{const event=createRequestEvent(new Request('https://conformance.test'));provideRequestEvent(event,()=>{let dispose!:()=>void;createRoot(d=>{dispose=d;event.response.headers.append('set-cookie',serializeCookie('a','1'));event.response.headers.append('set-cookie',serializeCookie('b','2'))});dispose();equal(event.response.headers.getSetCookie().length,2)})})
 doc('committed-header-mutation','Every stub Headers mutator throws in dev or reports and no-ops in production after commit.',()=>{for(const operation of ['set','append','delete']as const){const stub=createResponseStub();stub.headers.set('x-test','original');const event=createRequestEvent(new Request('https://conformance.test'),{response:stub});commitEventResponse(new Response('body'),event);const logged:unknown[]=[];const prior=console.error;console.error=(...args)=>{logged.push(args)};let error:unknown;try{if(operation==='delete')stub.headers.delete('x-test');else stub.headers[operation]('x-test','changed')}catch(e){error=e}finally{console.error=prior}if(isDev)ok(error);else equal(logged.length,1);equal(stub.headers.get('x-test'),'original')}})
 doc('redirect-status-selection','getExpectedRedirectStatus preserves a redirect status and uses 302 for page statuses.',()=>{for(const status of [301,302,303,307,308])equal(getExpectedRedirectStatus({...createResponseStub(),status}),status);for(const status of [200,404,500])equal(getExpectedRedirectStatus({...createResponseStub(),status}),302)})
 doc('stream-pipe-to','pipeTo writes to a web WritableStream and resolves only after render completion.',async()=>{const gate=deferred<number>();function App(){const value=createMemo(()=>gate.promise);return<Loading fallback={<b>waiting</b>}><span>{value()}</span></Loading>}const chunks:(string|Uint8Array)[]=[];let closed=false;const output=new WritableStream<string|Uint8Array>({write(chunk){chunks.push(chunk)},close(){closed=true}});const stream=renderToStream(App);const done=stream.pipeTo(output);equal(closed,false);gate.resolve(7);await done;equal(closed,true);ok(chunks.map(chunk=>typeof chunk==='string'?chunk:new TextDecoder().decode(chunk)).join('').includes('>7</span>'))})
 doc('chunk-transform','createSSRResponse transformChunk rewrites every outgoing HTML chunk.',async()=>{const event=createRequestEvent(new Request('https://conformance.test'));await provideRequestEvent(event,async()=>{const response=await createSSRResponse(renderToStream(()=><span>original</span>),event,{transformChunk:chunk=>chunk.replace('original','changed')});ok((await response.text()).includes('>changed</span>'))})})
 doc('ssr-head-defaults','SSR defaults content type and folds stub head values over responseInit at the commit seam.',()=>{const event=createRequestEvent(new Request('https://conformance.test'));event.response.status=201;event.response.headers.set('x-value','stub');const response=createSSRResponse('body',event,{responseInit:{status:202,headers:{'x-value':'option'}}});equal(response.status,201);equal(response.headers.get('x-value'),'stub');equal(response.headers.get('content-type'),'text/html; charset=utf-8');equal(event.response.committed,true)})
 doc('late-redirect-script','A post-flush Location on an integration-provided response stub is emitted as a nonce-bearing client redirect script.',async()=>{const response={status:200,statusText:'OK',headers:new Headers(),committed:false};const event=createRequestEvent(new Request('https://conformance.test'),{response});const gate=deferred<number>();await provideRequestEvent(event,async()=>{function App(){const value=createMemo(()=>gate.promise);return<Loading fallback={<b>pending</b>}><span>{value()}</span></Loading>}const output=await createSSRResponse(renderToStream(App),event,{nonce:'test-nonce'});equal(response.committed,true);response.headers.set('location','/later');gate.resolve(7);const html=await output.text();ok(html.includes('window.location'));ok(html.includes('/later'));ok(html.includes('nonce="test-nonce"'))})})
 doc('ambient-commit-event','commitEventResponse uses the ambient event when its event argument is omitted.',()=>{const event=createRequestEvent(new Request('https://conformance.test'));return provideRequestEvent(event,()=>{event.response.headers.set('x-ambient','yes');const response=commitEventResponse(new Response('body'));equal(response.headers.get('x-ambient'),'yes');equal(event.response.committed,true)})})
}else doc('client-request-scope-throws','provideRequestEvent throws on the client where no request scope exists.',()=>{let error:unknown;try{provideRequestEvent({request:new Request('https://conformance.test'),locals:{},response:{status:200,statusText:'OK',headers:new Headers(),committed:false}},()=>0)}catch(e){error=e}ok(error)})
export const remainingHttpCases=cases
