import {
	createSignal, createMemo, createContext, useContext, Show, For, Switch, Match, Repeat,
	Loading, Errored, Reveal, flush, untrack, configureClientErrors, createEffect,
} from 'solid-js'
import { render, renderToString, renderToStream, dynamic, clientOnly, isServer, isDev, Portal, generateHydrationScript } from '@solidjs/web'
import { controlledIterable, deferred, ticks } from '../../harness/timing'
import { equal, ok, throws, type DocCase } from './registry'

const cases: DocCase[]=[]
function doc(chapter:string,name:string,statement:string,run:DocCase['run']) {
	const file = { '02':'02-signals-derived-ownership.md', '03':'03-control-flow.md', '05':'05-async-data.md', '07':'07-dom.md', '12':'12-ssr-http.md' }[chapter]!
	cases.push({id:`${chapter}/${name}`,file,statement,run})
}
async function dom(App:()=>any, check:(el:HTMLElement)=>unknown|Promise<unknown>) {
	const el=document.createElement('div');document.body.append(el)
	let dispose:()=>void=()=>{}
	try { dispose=render(App,el);await ticks(2);await check(el) }
	finally { dispose();el.remove();await ticks(2) }
}
const clean=(s:string)=>s.replace(/<!--.*?-->/gs,'').replace(/ (?:_hk|data-hk)=(?:"[^"]*"|[^ >]*)/g,'').replace(/<script.*?<\/script>/gs,'').replace(/ disabled=""/g,' disabled')
function view(App:()=>any, expected:string) { return isServer ? equal(clean(renderToString(App)),expected) : dom(App,el=>equal(clean(el.innerHTML),expected)) }

doc('02','context-provider','The context itself is a component that takes a value prop and provides it to descendants.',()=>{const Context=createContext('light');function Child(){const value=useContext(Context);return <span>{value}</span>}return view(()=><Context value="dark"><Child/></Context>,'<span>dark</span>')})
doc('03','show-accessor','Non-keyed Show function children receive a narrowed accessor.',()=>view(()=><Show when={{name:'a'}}>{v=><span>{v().name}</span>}</Show>,'<span>a</span>'))
doc('03','show-keyed','Keyed Show function children receive the raw narrowed value.',()=>view(()=><Show when={{name:'a'}} keyed>{v=><span>{v.name}</span>}</Show>,'<span>a</span>'))
doc('03','show-fallback','Show supports element children and a fallback.',()=>view(()=><Show when={false} fallback={<b>empty</b>}><span>wrong</span></Show>,'<b>empty</b>'))
doc('03','for-identity','Default keyed For receives a raw item and an index accessor.',()=>view(()=><For each={['a','b']}>{(v,i)=><span>{v}{i()}</span>}</For>,'<span>a0</span><span>b1</span>'))
doc('03','for-positional','For keyed false receives an item accessor and a plain index.',()=>view(()=><For each={['a','b']} keyed={false}>{(v,i)=><span>{v()}{i}</span>}</For>,'<span>a0</span><span>b1</span>'))
doc('03','for-custom','Custom-keyed For receives two accessors.',()=>view(()=><For each={[{id:1},{id:2}]} keyed={v=>v.id}>{(v,i)=><span>{v().id}{i()}</span>}</For>,'<span>10</span><span>21</span>'))
doc('03','for-empty','Empty For inputs render the fallback.',()=>view(()=><For each={[]} fallback={<b>empty</b>}>{v=><span>{v}</span>}</For>,'<b>empty</b>'))
doc('03','repeat-offset','Repeat renders based on count and optional from; children receive a plain number.',()=>view(()=><Repeat count={2} from={3}>{i=><span>{i}</span>}</Repeat>,'<span>3</span><span>4</span>'))
doc('03','repeat-empty','Repeat renders fallback when count is zero.',()=>view(()=><Repeat count={0} fallback={<b>empty</b>}>{i=><span>{i}</span>}</Repeat>,'<b>empty</b>'))
doc('03','switch-first','Switch picks the first matching Match.',()=>view(()=><Switch><Match when={true}><b>first</b></Match><Match when={true}><b>second</b></Match></Switch>,'<b>first</b>'))
doc('03','switch-fallback','Switch supports a fallback.',()=>view(()=><Switch fallback={<b>empty</b>}><Match when={false}><b>wrong</b></Match></Switch>,'<b>empty</b>'))
doc('03','match-accessor','Non-keyed Match function children receive an accessor.',()=>view(()=><Switch><Match when={{name:'a'}}>{v=><span>{v().name}</span>}</Match></Switch>,'<span>a</span>'))
doc('03','match-keyed','Keyed Match function children receive the raw narrowed value.',()=>view(()=><Switch><Match when={{name:'a'}} keyed>{v=><span>{v.name}</span>}</Match></Switch>,'<span>a</span>'))
doc('03','error-fallback','Errored supports a callback receiving an error accessor and reset.',()=>{function Bad(){throw new Error('private-error');return <span/>} return view(()=><Errored fallback={e=><b>{String((e() as Error).message)}</b>}><Bad/></Errored>,`<b>${isServer&&!isDev?'Internal Server Error':'private-error'}</b>`)})
doc('03','dynamic-tag','dynamic returns a stable component driven by a reactive source.',()=>{const Tag=dynamic(()=>'article');return view(()=><Tag title="x">content</Tag>,'<article title="x">content</article>')})
doc('03','client-only-ssr','clientOnly renders props.fallback on the server and never starts the import.',async()=>{if(!isServer)return;let imports=0;const Only=clientOnly(async()=>{imports++;return {default:()=> <span>client</span>}});await view(()=><Only fallback={<b>fallback</b>}/>,'<b>fallback</b>');equal(imports,0)})
doc('05','client-source-ssr','With ssrSource client the server compute never runs.',async()=>{if(!isServer)return;let computes=0;function App(){const value=createMemo(()=>{computes++;return 7},{ssrSource:'client'});return <Loading fallback={<b>fallback</b>}><span>{value()}</span></Loading>}await view(App,'<b>fallback</b>');equal(computes,0)})
doc('05','declared-client-ssr','With loadingValue the server renders the declared first paint.',async()=>{if(!isServer)return;let computes=0;function App(){const value=createMemo(()=>{computes++;return 7},{ssrSource:'client',loadingValue:3});return <span>{value()}</span>}await view(App,'<span>3</span>');equal(computes,0)})

if(!isServer){
	doc('03','for-key-preservation','Custom keys preserve rows while either argument changes.',async()=>{let set!:(x:{id:number;n:string}[])=>void;await dom(()=>{const [rows,write]=createSignal([{id:1,n:'a'},{id:2,n:'b'}]);set=write;return <For each={rows()} keyed={r=>r.id}>{r=><span>{r().n}</span>}</For>},async el=>{const node=el.firstElementChild;set([{id:2,n:'B'},{id:1,n:'A'}]);await ticks(2);equal(el.lastElementChild===node,true);equal(el.textContent,'BA')})})
	doc('03','for-slot-preservation','For keyed false reuses by index.',async()=>{let set!:(x:string[])=>void;await dom(()=>{const [rows,write]=createSignal(['a','b']);set=write;return <For each={rows()} keyed={false}>{r=><span>{r()}</span>}</For>},async el=>{const node=el.firstElementChild;set(['c','d']);await ticks(2);equal(el.firstElementChild===node,true);equal(el.textContent,'cd')})})
	doc('03','error-once-reset','Once per error object: reset that recomputes the same failing node says nothing new.',async()=>{const error=new Error('same');let reports=0,reset!:()=>void;configureClientErrors({onError:()=>{reports++}});function Bad(){throw error;return <span/>}await dom(()=><Errored fallback={(e,retry)=>{reset=retry;return <b>{(e() as Error).message}</b>}}><Bad/></Errored>,async()=>{equal(reports,1);reset();await ticks(2);equal(reports,1)});configureClientErrors({})})
	doc('03','fallback-errors-parent','Errors in the fallback reach the parent boundary.',async()=>{function Bad(){throw new Error('child');return <span/>}await dom(()=><Errored fallback={e=><b>{(e() as Error).message}</b>}><Errored fallback={(_e)=>{throw new Error('fallback');return <i/>}}><Bad/></Errored></Errored>,el=>equal(el.textContent,'fallback'))})
	doc('05','loading-revalidation','Once Loading has rendered content it keeps stale content during revalidation.',async()=>{const gates=[deferred<number>(),deferred<number>()];let change!:(n:number)=>void;await dom(()=>{const [id,set]=createSignal(0);change=set;const value=createMemo(()=>gates[id()]!.promise);return <Loading fallback={<b>fallback</b>}><span>{value()}</span></Loading>},async el=>{equal(el.textContent,'fallback');gates[0]!.resolve(1);await ticks(2);equal(el.textContent,'1');change(1);await ticks(2);equal(el.textContent,'1');gates[1]!.resolve(2);await ticks(2);equal(el.textContent,'2')})})
	doc('05','loading-on-constant','The value returned by on is never compared; only the notification matters.',async()=>{const gates=[deferred<number>(),deferred<number>()];let change!:(n:number)=>void;await dom(()=>{const [id,set]=createSignal(0);change=set;const value=createMemo(()=>gates[id()]!.promise);return <Loading on={()=>{id();return 1}} fallback={<b>fallback</b>}><span>{value()}</span></Loading>},async el=>{gates[0]!.resolve(1);await ticks(2);change(1);await ticks(2);equal(el.textContent,'fallback');gates[1]!.resolve(2);await ticks(2);equal(el.textContent,'2')})})
	for(const order of ['sequential','together','natural'] as const) doc('03',`reveal-${order}`,`Reveal order ${order} coordinates sibling Loading boundaries.`,async()=>{const gates=[deferred<number>(),deferred<number>()];function Part(props:{id:number}){const v=createMemo(()=>gates[props.id]!.promise);return <span>{v()}</span>}await dom(()=><Reveal order={order}><Loading fallback={<b>A</b>}><Part id={0}/></Loading><Loading fallback={<b>B</b>}><Part id={1}/></Loading></Reveal>,async el=>{equal(el.textContent,'AB');gates[1]!.resolve(2);await ticks(2);equal(el.textContent,order==='natural'?'A2':'AB');gates[0]!.resolve(1);await ticks(2);equal(el.textContent,'12')})})
	doc('03','client-only-once','The clientOnly importer is invoked at most once no matter how many instances render.',async()=>{let imports=0;const Only=clientOnly(async()=>{imports++;return {default:()=> <span>client</span>}});await dom(()=><><Only fallback={<b/>}/><Only fallback={<b/>}/></>,async el=>{await ticks(2);equal(imports,1);equal(el.textContent,'clientclient')})})
	doc('07','events-once','Event handlers bind once; the binding expression is not reactive.',async()=>{let set!:(v:boolean)=>void;const seen:string[]=[];await dom(()=>{const [toggle,write]=createSignal(false);set=write;return <button onClick={toggle()?()=>{seen.push('b')}:()=>{seen.push('a')}}>click</button>},async el=>{set(true);await ticks(2);el.querySelector('button')!.click();equal(seen,['a'])})})
	doc('07','ref-array','Ref arrays are flattened and called with the element.',async()=>{const refs:Element[]=[];await dom(()=><div ref={[(el)=>{refs.push(el)},[(el)=>{refs.push(el)}]]}/>,el=>{equal(refs.length,2);equal(refs[0]===el.firstElementChild,true);equal(refs[0]===refs[1],true)})})
	doc('07','root-events-dispose','Delegated listeners are disposed when the render root is disposed.',async()=>{let calls=0;const el=document.createElement('div');document.body.append(el);const close=render(()=><button onClick={()=>{calls++}}>click</button>,el);const button=el.querySelector('button')!;button.click();equal(calls,1);close();el.append(button);button.click();equal(calls,1);el.remove()})
	doc('07','shadow-root','Rendering into a ShadowRoot attaches delegated listeners to that shadow root.',async()=>{let calls=0;const el=document.createElement('div');document.body.append(el);const shadow=el.attachShadow({mode:'open'});const close=render(()=><button onClick={()=>{calls++}}>click</button>,shadow);try{shadow.querySelector('button')!.click();equal(calls,1)}finally{close();el.remove()}})
	doc('07','portal-events','Portal registers outside-root mount points as additional listener containers.',async()=>{let calls=0;const mount=document.createElement('div');document.body.append(mount);try{await dom(()=><Portal mount={mount}><button onClick={()=>{calls++}}>click</button></Portal>,()=>{mount.querySelector('button')!.click();equal(calls,1)})}finally{mount.remove()}})
}
doc('07','class-compose','class accepts string, object or array of strings and objects.',()=>view(()=><div class={['card',{active:true,hidden:false},['nested']]}/>,'<div class="card active nested"></div>'))
doc('07','boolean-attribute','Boolean literals add/remove the attribute; strings preserve true.',()=>view(()=><><button disabled={true}/><button disabled={false}/><div data-enabled="true"/></>,'<button disabled></button><button></button><div data-enabled="true"></div>'))
if(isServer){
	doc('12','sync-fallback','renderToString is synchronous; async boundaries render their fallbacks.',()=>{function App(){const v=createMemo(()=>new Promise<number>(()=>{}));return <Loading fallback={<b>fallback</b>}><span>{v()}</span></Loading>}return view(App,'<b>fallback</b>')})
	doc('12','stream-thenable','Awaiting renderToStream resolves with fully resolved HTML.',async()=>{function App(){const v=createMemo(()=>Promise.resolve(7));return <Loading fallback={<b>fallback</b>}><span>{v()}</span></Loading>}const html=await renderToStream(App);ok(html.includes('>7</span>'))})
	doc('12','stream-readable','readable yields Uint8Array bytes suitable for a Response body.',async()=>{const result=renderToStream(()=><span>7</span>);const reader=result.readable.getReader();const chunk=await reader.read();ok(chunk.value instanceof Uint8Array);await reader.cancel()})
	doc('12','one-consumer','Exactly one consumption surface may be used per render.',async()=>{const result=renderToStream(()=><span>7</span>);const first=result.readable;throws(()=>result.pipe({write(){},end(){}}));await first.cancel()})
	doc('12','hydration-script','generateHydrationScript returns the bootstrap string with nonce.',()=>{const html=generateHydrationScript({nonce:'test-nonce'});ok(html.includes('nonce="test-nonce"'));ok(html.includes('_$HY'))})
	doc('05','defer-stream','deferStream true defers the SSR stream flush until the first value resolves.',async()=>{const gate=deferred<number>();function App(){const value=createMemo(()=>gate.promise,{deferStream:true});return <Loading fallback={<b>fallback</b>}><span>{value()}</span></Loading>}const chunks:string[]=[];const result=renderToStream(App);const done=deferred<void>();result.pipe({write:c=>{chunks.push(c)},end:()=>{done.resolve()}});await ticks(2);equal(chunks.length,0);gate.resolve(7);await done.promise;ok(chunks.join('').includes('>7</span>'));ok(!chunks.join('').includes('fallback'))})
}
export const renderCases=cases
