import {createRoot,createSignal,createMemo,createEffect,createRenderEffect,createOptimistic,action,affects,Loading,OBSERVE,flush,getOwner,untrack} from 'solid-js'
import {isDev,render} from '@solidjs/web'
import {attribution} from 'solid-js/attribution'
import {deferred,ticks} from '../../harness/timing'
import {ok,equal,runCases,type DocCase} from './registry'
import {observed} from './diagnostic-cases'
const options={log:false,checks:false,graphGrowth:false,holds:{infoMs:0,warnMs:0},longHolds:false,waterfalls:false,stackedHolds:false,abandonedFlights:false,optimisticReverts:true} as const
const cases:DocCase[]=[{id:'08/hold-affects-declaration',file:'08-dev-diagnostics.md',statement:'L525: action affects declaration acknowledges held writes even without a pending reader.',async run(){if(!isDev)return;const release=attribution.enable(options),gate=deferred<number>(),wait=deferred<void>();let dispose!:()=>void
 try{const [run]=createRoot(d=>{dispose=d;const[r,w]=createSignal(0,{name:'source'});const m=createMemo(()=>r()?gate.promise:0,{name:'answer'});createRenderEffect(m,()=>{});const run=action(function* save(){affects(m);w(1);yield wait.promise});flush();return[run] as const});const result=await observed(async()=>{const done=run();flush();await ticks(4);gate.resolve(2);await ticks(4);wait.resolve();await done;await ticks(8);flush()});const record=attribution.history('hold').at(-1)!;ok(record);equal(record.silent,false);ok(record.acknowledgements.some(a=>a.kind==='affects'));equal(result.events.filter(e=>e.code==='SILENT_HOLD'),[])}finally{dispose?.();release()}}},
{id:'08/unrevealed-loading-no-hold',file:'08-dev-diagnostics.md',statement:'L525: a never-revealed Loading renders fallback without parking a hold; first source landing commits content.',async run(){if(!isDev)return;const release=attribution.enable(options),gate=deferred<number>(),root=document.createElement('div');document.body.append(root);let data!:()=>number;const close=render(()=>{data=createMemo(()=>gate.promise,{name:'initial-answer'});return <Loading fallback={<i>pending</i>}><b>{data()}</b></Loading>},root)
 try{flush();await ticks(4);equal(root.textContent,'pending');equal(attribution.history('hold'),[]);gate.resolve(17);await ticks(8);flush();equal(root.textContent,'17');equal(attribution.history('hold'),[])}finally{close();root.remove();release()}}},
{id:'08/optimistic-companion-exemptions',file:'08-dev-diagnostics.md',statement:'L567: pending/latest companions and derived optimistic promotion are not corrective guesses.',async run(){if(!isDev)return;const release=attribution.enable(options),gate=deferred<number>();let dispose!:()=>void;const seen:number[]=[]
 try{const [write]=createRoot(d=>{dispose=d;const[r,w]=createSignal(0);const m=createMemo(()=>r()?gate.promise:0,{name:'answer'});const[overlay,setOverlay]=createOptimistic(()=>m(),{name:'guess'});const doubled=createMemo(()=>overlay()*2);createRenderEffect(doubled,v=>{seen.push(v)});flush();return[(n:number)=>{w(n);setOverlay(5)}] as const});const result=await observed(async()=>{write(1);flush();await ticks(4);gate.resolve(5);await ticks(8);flush()});equal(seen.at(-1),10);equal(result.events.filter(e=>e.code==='OPTIMISTIC_REVERTED'),[])}finally{dispose?.();release()}}},
]
;(window as any).rootResponsiveness=runCases(cases)
