import {test,expect} from 'bun:test'
import {createServer} from 'vite'
import {chromium} from 'playwright'
import {resolve} from 'node:path'
import {mkdir,rm,cp} from 'node:fs/promises'
test('RFC11 L15: components:true generated entries wire real Vite dev SSR and Chrome hydration, with the same use-server compiler contract',async()=>{
 const manifest=await Bun.file('.upstream/vite-built.json').json(),solid=(await import(manifest.directory+'/dist/esm/index.mjs')).default
 const root=resolve('.scratch','vite-components-'+process.pid);await mkdir(root,{recursive:true});await cp('tracks/docs/vite-components-fixture/src',root+'/src',{recursive:true})
 const server=await createServer({root,configFile:false,plugins:solid({start:true,ssr:true,serverFunctions:{components:true},diagnostics:false,performanceTracks:false}),ssr:{noExternal:['solid-js','@solidjs/web','@solidjs/signals','seroval','seroval-plugins']},server:{host:'127.0.0.1',port:0},logLevel:'silent',optimizeDeps:{noDiscovery:true}})
 const browser=await chromium.launch({channel:'chrome',headless:true})
 try{await server.listen();const address=server.httpServer!.address() as {port:number},url='http://127.0.0.1:'+address.port+'/';const debug:any={};for(const id of ['virtual:solid-ssr-entry-server.tsx','virtual:solid-ssr-entry-client.tsx','virtual:solid-ssr-document.tsx','virtual:solid-server-function-handler']){const loaded=await server.pluginContainer.load(id,{ssr:true});debug[id]=typeof loaded==='string'?loaded:loaded?.code};await Bun.write('artifacts/vite-components-code.json',JSON.stringify(debug,null,2));const response=await fetch(url,{headers:{accept:'text/html'},signal:AbortSignal.timeout(15000)}),html=await response.text();expect(response.status).toBe(200);await Bun.write('artifacts/vite-components-html.html',html);expect(html).toContain('server-only-marker-');const page=await browser.newPage(),messages:string[]=[];await page.route('**/favicon.ico',route=>route.fulfill({status:204}));page.on('pageerror',e=>messages.push(String(e)));page.on('console',m=>{if(m.type()==='error'||m.type()==='warning')messages.push(m.text())});await page.goto(url);await page.locator('button').click();await page.waitForFunction(()=>document.querySelector('button')?.textContent==='1');expect(await page.locator('button').textContent()).toBe('1');expect(await page.locator('h1').textContent()).toBe('server-only-marker-1');expect(messages).toEqual([]);const clientCode=await(await fetch(url+'src/functions.tsx')).text();expect(clientCode).not.toContain('server-only-marker');const results={manifest,status:response.status,html,clientCode,messages,dom:await page.locator('main').textContent()};await Bun.write('artifacts/vite-components.json',JSON.stringify(results,null,2))}finally{await browser.close();await server.close();await rm(root,{recursive:true,force:true})}
},90000)
