import {test,expect} from 'bun:test'
import {chromium} from 'playwright'
import {resolve} from 'node:path'
import {rm} from 'node:fs/promises'
import {buildFrames} from './build'
test('11:L118 router claims/frame query preload, warm navigation, owner cleanup and multi-frame single-flight',async()=>{
 const mode=(process.env.BUILD_MODE??'development') as 'development'|'production';const dir=resolve('.build','routerframes-'+process.pid+'-'+mode)
 await buildFrames(dir,mode,{client:'tracks/frames/router-client.tsx',server:'tracks/frames/router-server.tsx'})
 const ssr=await import(dir+'/router-server.js') as typeof import('./router-server')
 const server=Bun.serve({port:0,hostname:'127.0.0.1',fetch:async request=>{const url=new URL(request.url);if(url.pathname.startsWith('/_server'))return ssr.handle(request);if(url.pathname.endsWith('.js'))return new Response(Bun.file(dir+url.pathname),{headers:{'content-type':'text/javascript'}});if(url.pathname==='/favicon.ico')return new Response(null,{status:204});if(url.searchParams.has('hydrate'))return new Response(ssr.documentStream().readable,{headers:{'content-type':'text/html'}});return new Response('<html><body><div id="root"></div><script type="module" src="/router-client.js"></script></body></html>',{headers:{'content-type':'text/html'}})}})
 const browser=await chromium.launch({channel:'chrome',headless:true});const receipt:any[]=[]
 try{for(const surface of ['csr','hydrate']){const page=await browser.newPage();const messages:string[]=[];page.on('pageerror',e=>messages.push(e.message));page.on('console',m=>{if(['warning','error'].includes(m.type()))messages.push(m.text())});await page.goto(server.url+(surface==='hydrate'?'?hydrate':''));await page.waitForFunction(()=>!!(window as any).routerFrames);const pause=()=>page.evaluate(()=>(window as any).routerFrames.pause());await pause();expect(await page.locator('h1').allTextContents()).toEqual(['story-1-v'+(surface==='csr'?0:1),'story-1-v'+(surface==='csr'?0:1)]);if(surface==='hydrate'){expect(await page.locator('[data-frame-link][data-active]').count()).toBe(process.env.EXPECT_FINDINGS==='1'?2:1);await page.locator('[data-counter]').nth(1).click();expect(await page.locator('[data-counter]').allTextContents()).toEqual(process.env.EXPECT_FINDINGS==='1'?['0','1']:['0','0']);receipt.push({surface,finding:'011',requests:await page.evaluate(()=>(window as any).routerFrames.requests),messages});await page.close();continue};expect(await page.locator('[data-frame-link][data-active]').count()).toBe(2);expect(await page.locator('[data-frame-link][aria-current=page]').count()).toBe(2);const start=await page.evaluate(()=>(window as any).routerFrames.requests.length);expect(start).toBe(surface==='csr'?1:0)
 await page.evaluate(()=>{(window as any).routerFrames.incOutside();(window as any).routerFrames.preload('/story/2',{preloadData:true})});await pause();const pre=await page.evaluate(()=>(window as any).routerFrames.requests.length);expect(pre-start).toBe(1);await page.evaluate(()=>(window as any).routerFrames.navigate('/story/2'));await pause();expect(await page.locator('[data-story="2"]').count()).toBe(2);expect(await page.evaluate(()=>(window as any).routerFrames.requests.length)).toBe(pre);await page.locator('[data-counter]').first().click();expect(await page.locator('[data-counter]').allTextContents()).toEqual(['1','0']);await page.evaluate(()=>{(window as any).detachedLink=document.querySelector('[data-frame-link]');(window as any).routerFrames.navigate('/empty')});await pause();expect(await page.locator('aside').textContent()).toBe('empty');const detached=await page.evaluate(()=>(window as any).detachedLink.outerHTML);await page.evaluate(()=>(window as any).routerFrames.navigate('/story/1'));await pause();expect(await page.evaluate(()=>(window as any).routerFrames.requests.length)).toBe(pre);expect(await page.evaluate(()=>(window as any).detachedLink.outerHTML)).toBe(detached);expect(await page.locator('output').textContent()).toBe('1');expect(await page.locator('[data-frame-link][data-active]').count()).toBe(2)
 await page.evaluate(()=>{document.querySelector<HTMLFormElement>('form')!.requestSubmit()});await page.waitForFunction(()=>document.querySelectorAll('form[aria-busy=true]').length===1);expect(await page.locator('form[aria-busy=true]').count()).toBe(1);for(let i=0;!ssr.release&&i<100;i++)await new Promise(r=>setTimeout(r,5));ssr.release();await page.waitForFunction(()=>(window as any).routerFrames.result!==undefined);const result=await page.evaluate(()=>(window as any).routerFrames.result);await pause();expect(await page.locator('form[aria-busy]').count()).toBe(0);expect(result).toBe(surface==='csr'?1:2);expect(await page.locator('h1').allTextContents()).toEqual(['story-1-v'+result,'story-1-v'+result]);await page.evaluate(()=>(window as any).routerFrames.navigate('/story/2'));await pause();expect(await page.locator('h1').allTextContents()).toEqual(['story-2-v'+result,'story-2-v'+result]);const requests=await page.evaluate(()=>(window as any).routerFrames.requests);expect(requests.length).toBe(pre+1);expect(requests.filter((r:any)=>r.method==='POST').at(-1).singleFlight).toBeTruthy();expect(messages).toEqual([]);receipt.push({surface,requests,messages,result});await page.evaluate(()=>(window as any).routerFrames.close());await page.close()}}
 finally{await Bun.write('artifacts/routerframes-'+mode+'.json',JSON.stringify(receipt,null,2));await browser.close();server.stop(true);await rm(dir,{recursive:true,force:true})}
},120000)
