import {test,expect} from 'bun:test';
import {chromium} from 'playwright';
import {resolve} from 'node:path';
import {rm} from 'node:fs/promises';
import {build,type BuildMode} from '../../scripts/build';
for(const mode of ['development','observe','production'] as BuildMode[])test('RFC10 L302:2 superseded reactive calls complete and populate their cache without rendering stale answers '+mode,async()=>{
 const dir=resolve('.build','superseded-'+process.pid+'-'+mode);await build(dir,mode,{client:['tracks/frames/superseded-call/client.tsx'],server:[]});const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch:request=>new URL(request.url).pathname.endsWith('.js')?new Response(Bun.file(dir+new URL(request.url).pathname),{headers:{'content-type':'text/javascript'}}):new Response('<div id="root"></div><script type="module" src="/client.js"></script>',{headers:{'content-type':'text/html'}})});const browser=await chromium.launch({channel:'chrome',headless:true});
 try{const page=await browser.newPage();const errors:string[]=[];page.on('pageerror',e=>errors.push(String(e)));await page.goto(String(server.url));await page.waitForFunction(()=>(window as any).superseded?.snapshot().requests.length===1);await page.evaluate(()=>(window as any).superseded.set(2));await page.waitForFunction(()=>(window as any).superseded.snapshot().requests.length===2);const before=await page.evaluate(()=>(window as any).superseded.snapshot());expect(before).toMatchObject({requests:[{key:1,aborted:false},{key:2,aborted:false}],cache:{},history:[],text:'pending'});await page.evaluate(()=>(window as any).superseded.settle(2));await page.waitForFunction(()=>(window as any).superseded.snapshot().text==='2',null,{timeout:1000});await page.evaluate(()=>(window as any).superseded.settle(1));await page.waitForFunction(()=>Object.keys((window as any).superseded.snapshot().cache).length===2);await page.waitForTimeout(20);const after=await page.evaluate(()=>(window as any).superseded.snapshot());expect(after).toMatchObject({requests:before.requests,cache:{1:1,2:2},history:[2],text:'2'});expect(errors).toEqual([]);await page.evaluate(()=>(window as any).superseded.close())}finally{await browser.close();server.stop(true);await rm(dir,{recursive:true,force:true})}
},30000);
