import {configureServerFunctionsClient,createServerReference,GET,live,invoke} from '@solidjs/web/server-functions/client';
const fn=live(GET(createServerReference('loop')));
async function scenario(kind:string){
 const retryKind=kind.startsWith('retry');const retryStatus=kind==='retry'?429:kind==='retry-named-404'?404:Number(kind.slice(6));let reconnects=0;const timers:ReturnType<typeof setTimeout>[]=[];const times:number[]=[],statuses:string[]=[],values:any[]=[],args:any[]=[];let index=0,cleanups=0;const abort=new AbortController();
 configureServerFunctionsClient({prepareRequest:init=>init,fetch:async(_address,init)=>{times.push(performance.now());if(init.signal?.aborted)throw new DOMException('aborted','AbortError');const n=index++;if(n===1&&(kind==='definite'||retryKind))return new Response('refused',{status:kind==='definite'?404:retryStatus,headers:kind==='retry'?{'Retry-After':'0'}:kind==='retry-named-404'?{'Retry-After':'1'}:{}});return new Response(String(n))},responseHandler:{handle(response,ctx){args.push(ctx.args);if(response.status>=400)return undefined;return response.text().then(text=>{
  const n=Number(text);if(kind==='backoff'&&n===1)throw new Error('repeat connect failure');
  return (async function*(){try{yield {n,nested:{identity:n},nestedStream:(async function*(){yield n})()};if(kind==='backoff'&&n<3||kind!=='backoff'&&n===0)throw new Error('connection died')}finally{cleanups++}})();
 })}}});
 const source=kind==='abort'?invoke(fn,{signal:abort.signal}):fn();source.onstatus=(status:string)=>{statuses.push(status);if(status==='reconnecting')reconnects++;if(status==='reconnecting'&&(kind==='online'||kind==='definite'||retryKind)&&(kind!=='retry-named-404'||reconnects===1))timers.push(setTimeout(()=>window.dispatchEvent(new Event('online')),15));if(status==='reconnecting'&&kind==='abort')timers.push(setTimeout(()=>abort.abort(),15))};
 const iterator=source[Symbol.asyncIterator]();let error:any;try{values.push((await iterator.next()).value);values.push((await iterator.next()).value);if(kind==='backoff')values.push((await iterator.next()).value)}catch(e){error=e}
 const nestedValues=await Promise.all(values.map(async answer=>{const seen=[];for await(const value of answer.nestedStream)seen.push(value);return seen}));const fresh=values.every((value,i)=>!i||value!==values[i-1]&&value.nestedStream!==values[i-1].nestedStream);await iterator.return!();for(const timer of timers)clearTimeout(timer);await Promise.resolve();return {times:times.map(t=>t-times[0]!),statuses,values,nestedValues,fresh,cleanups,args,error:error?{name:error.name,status:error.status}:null};
}
const results:any={};for(const kind of ['backoff','online','definite','retry','retry-408','retry-425','retry-429','retry-named-404','abort'])results[kind]=await scenario(kind);
(window as any).result=results;
