// Merge independently audited source units. A red counterexample is covered,
// while an executable but absent assertion remains uncovered.
import {existsSync} from 'node:fs'
const base=await Bun.file('tracks/docs/inventory.json').json()
const units=new Map<string,any>(base.statements.map((entry:any)=>[entry.id,entry]))
const files=['core-coverage.json','core-fence-coverage.json','frames-coverage.json','12-server-hooks-coverage.json','inventory-08-early-fences.json','inventory-08-reference.json','inventory-08-quick-reference.json','inventory-08-runtime-server.json','inventory-08-cost-options.json','inventory-08-late.json','inventory-08-late-final.json','inventory-08-root.json','inventory-08-fence-root.json','inventory-router-final.json']
for(const file of files){if(!existsSync('tracks/docs/'+file))continue;const value=await Bun.file('tracks/docs/'+file).json();for(const entry of Array.isArray(value)?value:value.entries){const prior=units.get(entry.id);if(!prior)throw new Error('Unknown source locator '+entry.id+' in '+file);units.set(entry.id,{...prior,...entry})}}
const statements=[...units.values()].sort((a,b)=>a.file.localeCompare(b.file)||a.line-b.line||a.id.localeCompare(b.id))
for(const entry of statements){entry.classification=entry.status==='not-behavioral'?'not-behavioral':'behavioral';if(entry.status==='covered'&&!entry.coverage.length)throw new Error('Missing proof '+entry.id);if(['untestable','not-behavioral'].includes(entry.status)&&!entry.reason)throw new Error('Missing classification reason '+entry.id)}
const count=(entries:any[],status:string)=>entries.filter(entry=>entry.status===status).length
const summary={raw:statements.length,behavioral:statements.filter(entry=>entry.classification==='behavioral').length,covered:count(statements,'covered'),uncovered:count(statements,'uncovered'),untestable:count(statements,'untestable'),nonBehavioral:count(statements,'not-behavioral')}
await Bun.write('tracks/docs/inventory.json',JSON.stringify({...base,statements,summary},null,2)+'\n')
await Bun.write('artifacts/docs-inventory-summary.json',JSON.stringify({commit:base.commit,...summary},null,2)+'\n')
const escape=(value:string)=>value.replaceAll('|','\\|').replaceAll('\n',' ')
const source=(entry:any)=>`[${entry.id}](https://github.com/solidjs/solid/blob/${base.commit}/documentation/solid-2.0/${entry.file}#L${entry.line})`
const sections=[...new Set(statements.map(entry=>entry.file))]
const body=`---\ntype: Reference\ntitle: Solid 2 behavioral statement coverage\nstatus: ${summary.uncovered?'partial':'complete'}\nupstream_commit: ${base.commit}\ndescription: 全文及代码示例的逐项合同、测试证据与不可测试原因。\n---\n\n# 文档覆盖\n\n来源为 [Solid next documentation/solid-2.0](https://github.com/solidjs/solid/tree/${base.commit}/documentation/solid-2.0)。当前全文索引 ${summary.raw} 个原始源单元，分类为 ${summary.behavioral} 个行为声明、${summary.nonBehavioral} 个导航、解释或未来设计单元。代码块完整原文索引见 fenced-examples.json；注释与独立代码合同保留自己的稳定 locator，不能以代码块数量替代行为分母。\n\n**covered / total：${summary.covered} / ${summary.behavioral}**；另有 ${summary.untestable} 个不可测试声明和 ${summary.uncovered} 个可测试但尚缺断言的声明。covered 表示已有检查合同的断言，也包括 findings 中已缩减的红例；不表示框架全通过。一个 compound statement 的全部保证都得到证明才记为 covered。重复合同保留各自 source locator，可引用同一测试。\n\n## 按文档统计\n\n| 文件 | 行为总数 | covered | uncovered | untestable | 非行为 |\n| --- | ---: | ---: | ---: | ---: | ---: |\n${sections.map(file=>{const entries=statements.filter(e=>e.file===file);return '| '+file+' | '+entries.filter(e=>e.classification==='behavioral').length+' | '+count(entries,'covered')+' | '+count(entries,'uncovered')+' | '+count(entries,'untestable')+' | '+count(entries,'not-behavioral')+' |'}).join('\n')}\n\n## 不可测试声明\n\n| 来源 | 声明 | 原因 |\n| --- | --- | --- |\n${statements.filter(e=>e.status==='untestable').map(e=>'| '+source(e)+' | '+escape(e.statement)+' | '+escape(e.reason)+' |').join('\n')}\n\n## 尚缺断言\n\n| 来源 | 声明 | 当前原因 |\n| --- | --- | --- |\n${statements.filter(e=>e.status==='uncovered').map(e=>'| '+source(e)+' | '+escape(e.statement)+' | '+escape(e.reason??'尚未完成完整保证的可执行断言。')+' |').join('\n')}\n\n## 已覆盖合同\n\n| 来源 | 声明 | 可执行证据 |\n| --- | --- | --- |\n${statements.filter(e=>e.status==='covered').map(e=>'| '+source(e)+' | '+escape(e.statement)+' | '+escape(e.coverage.join('; '))+' |').join('\n')}\n`
await Bun.write('tracks/docs/COVERAGE.md',body)
console.log(JSON.stringify({commit:base.commit,...summary}))
